import json

chunks_list = [
{"choices": [{"delta": {"content":'{'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'   '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'title'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'Ein'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'stein'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Orders'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' a'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Cat'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'apult'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'   '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'spe'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'akers'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' {'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'1'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' {'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'name'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'Albert'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'gender'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'m'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'"'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' },'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'2'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' {'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'name'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'Herr'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Schmidt'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'gender'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'m'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'"'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' }'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'   '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' },'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'   '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'all'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_turn'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'s'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' ['}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' {'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'target'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_language'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'Ich'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' hätte'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' gerne'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' eine'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Kat'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'apult'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":','}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' bitte'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'.",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'native'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_language'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'I'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' would'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' like'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' a'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' cat'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'apult'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":','}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' please'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'.",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'turn'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_nr'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'1'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'1'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'gender'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'m'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'"'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' },'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' {'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'target'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_language'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'Eine'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Kat'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'apult'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'?'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Herr'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Einstein'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":','}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' w'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'of'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'ür'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' brauchen'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Sie'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' das'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'?",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'native'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_language'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'A'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' cat'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'apult'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'?'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Mr'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'.'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' Einstein'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":','}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' what'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' do'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' you'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' need'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' it'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' for'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'?",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'turn'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_nr'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'2'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'speaker'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'_'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'2'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'",'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'           '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'gender'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'":'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' "'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'m'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'"'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'       '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' }'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'   '}, "finish_reason": None}]},
{"choices": [{"delta": {"content":' ]'}, "finish_reason": None}]},
{"choices": [{"delta": {"content":''}, "finish_reason": None}]},
{"choices": [{"delta": {"content":'}'}, "finish_reason": "the end my friend"}]}
]


class Delta:
    def __init__(self, content):
        self.content = content

class Choice:
    def __init__(self, delta, finish_reason):
        self.delta = delta
        self.finish_reason = finish_reason

class ChatGPTResponse:
    def __init__(self, choices):
        self.choices = choices


simulated_response = []
for json_data in chunks_list:
    # data = json.loads(json_data)
    choices = [Choice(Delta(choice['delta']['content']), choice['finish_reason']) for choice in json_data['choices']]
    chat_gpt_response = ChatGPTResponse(choices)
    simulated_response.append(chat_gpt_response)
