chunks_list = [
{"choices": [{"delta": {"content": '{\n',}, "finish_reason": None}]},
{"choices": [{"delta": {"content": '   ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'title', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'Ein', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'stein', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Orders', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' a', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Cat', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'apult', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '   ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'spe', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'akers', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' {\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '1', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' {', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'name', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'Albert', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'gender', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'm', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '"', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' },\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '2', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' {', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'name', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'Herr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Müller', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'gender', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'm', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '"', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' }\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '   ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' },\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '   ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'all', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_turn', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 's', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' [\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' {\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'target', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_language', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'G', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'uten', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Tag', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ',', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Herr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Müller', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Ich', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' möchte', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' eine', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Kat', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'apult', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' bestellen', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'native', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_language', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'Good', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' day', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ',', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Mr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Müller', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' I', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' would', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' like', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' to', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' order', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' a', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' cat', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'apult', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'turn', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_nr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '1', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '1', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'gender', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'm', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '"\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' },\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' {\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'target', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_language', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'Eine', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Kat', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'apult', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ',', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Herr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Einstein', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '?', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Das', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' ist', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' eine', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' ungewöhn', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'liche', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Bestellung', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'native', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_language', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'A', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' cat', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'apult', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ',', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Mr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' Einstein', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '?', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' That', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' is', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' an', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' unusual', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' order', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '.",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'turn', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_nr', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '2', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'speaker', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '_', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '2', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '",\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '           ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'gender', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '":', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' "', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": 'm', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '"\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '       ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' }\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '   ', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": ' ]\n', }, "finish_reason": None}]},
{"choices": [{"delta": {"content": '}' }, "finish_reason": "the end"}]},
]


class Delta:
    def __init__(self, content):
        self.content = content

class Choice:
    def __init__(self, delta, finish_reason):
        self.delta = delta
        self.finish_reason = finish_reason

class ChatGPTResponse:
    def __init__(self, choices):
        self.choices = choices


simulated_response = []
for json_data in chunks_list:
    choices = [Choice(Delta(choice['delta']['content']), choice['finish_reason']) for choice in json_data['choices']]
    chat_gpt_response = ChatGPTResponse(choices)
    simulated_response.append(chat_gpt_response)
