language_codes = {
"Afrikaans (South Africa)": "af-ZA",
"Arabic (Egypt)":"ar-EG",
"Arabic (State of Palestine)":"ar-PS",
"Arabic (Syria)": "ar-SY",
"Arabic (Tunisia)": "ar-TN",
"Azerbaijani (Azerbaijan)": "az-AZ",
"Bengali (India)": "bn-IN",
"Catalan (Spain)": "ca-ES",
"Chinese, Mandarin (Simplified, China)": "cmn-Hans-CN",
"Chinese, Cantonese (Traditional Hong Kong)":"yue-Hant-HK",
"Danish (Denmark)": "da-DK",
"Dutch (Netherlands)": "nl-NL",
"English (United Kingdom)":"en-GB",
"English (United States)": "en-US",
"French (France)": "fr-FR",
"German (Germany)": "de-DE",
"Greek (Greece)":"el-GR",
"Hindi (India)":"hi-IN",
"Italian (Italy)": "it-IT",
"Japanese (Japan)": "ja-JP",
"Korean (South Korea)": "ko-KR",
"Portuguese (Brazil)": "pt-BR",
"Portuguese (Portugal)": "pt-PT",
"Russian (Russia)": "ru-RU",
"Spanish (Mexico)": "es-MX",
"Spanish (Spain)": "es-ES",
"Tamil (India)": "ta-IN",
"Turkish (Turkey)": "tr-TR",
"Zulu (South Africa)": "zu-ZA"
}
