script = ["narrator_opening_phrases_5_0",
"narrator_opening_phrases_5_1",
"lesson_title_narrator",
"narrator_navigation_phrases_7",  #listen
# (add later) Narrator introduces the whole conversation first:
"sentence_0_target",
"sentence_1_target",
"sentence_2_target",
"sentence_3_target",
"sentence_4_target",
"sentence_5_target",
"sentence_6_target",
"sentence_7_target",
"sentence_8_target",
"sentence_9_target",
"one_second_break",
"one_second_break",

# Sentence 0
"sentence_0_narrator_explanation",
"one_second_break",
"narrator_navigation_phrases_7", #listen
"one_second_break",
"sentence_0_target",
"narrator_repetition_phrases_0_0",
# (create this audio file) "sentence_0_split_sentence_0_native_narrator", 

# Chunk 1
"sentence_0_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_0_1",
"sentence_0_split_sentence_0_target",
"five_second_break",
"sentence_0_split_sentence_0_target",
"five_second_break",
"narrator_navigation_phrases_11", #It means
"sentence_0_split_sentence_0_native",
"one_second_break",
"sentence_0_split_sentence_0_narrator_fun_fact",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_0_target",
"five_second_break",
"sentence_0_split_sentence_0_target",
"five_second_break",
"sentence_0_split_sentence_0_target_0",
"five_second_break",
"sentence_0_split_sentence_0_target_0",
"five_second_break",
"sentence_0_split_sentence_0_target_1",
"five_second_break",
"sentence_0_split_sentence_0_target_1",
"five_second_break",
"sentence_0_split_sentence_0_target",
"five_second_break",

# Chunk 2
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_0_split_sentence_1_native",
"one_second_break",
"sentence_0_split_sentence_1_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_1_target",
"five_second_break",
"sentence_0_split_sentence_1_target",
"five_second_break",
"sentence_0_split_sentence_1_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_0_split_sentence_1_target",
"five_second_break",
"sentence_0_split_sentence_1_target",
"five_second_break",
"sentence_0_split_sentence_1_target_0",
"five_second_break",
"sentence_0_split_sentence_1_target_0",
"five_second_break",
"sentence_0_split_sentence_1_target",
"five_second_break",

# Chunk 3
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_0_split_sentence_2_native",
"one_second_break",
"sentence_0_split_sentence_2_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_2_target",
"five_second_break",
"sentence_0_split_sentence_2_target",
"five_second_break",
"sentence_0_split_sentence_2_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_0_split_sentence_2_target",
"five_second_break",
"sentence_0_split_sentence_2_target",
"five_second_break",
"sentence_0_split_sentence_2_target_0",
"five_second_break",
"sentence_0_split_sentence_2_target_0",
"five_second_break",
"sentence_0_split_sentence_2_target",
"five_second_break",

# Chunk 4
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_0_split_sentence_3_native",
"one_second_break",
"sentence_0_split_sentence_3_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",

#Remember part:
"narrator_navigation_phrases_8_0", # Do you remember how to say...
"sentence_0_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_3_1", # Give it a try
"five_second_break",
"sentence_0_split_sentence_0_target",
"five_second_break",
"sentence_0_split_sentence_0_target",
"five_second_break",

# Wrap up
"narrator_navigation_phrases_10", #listen
"one_second_break",
"sentence_0_target",
"five_second_break",
"sentence_0_target",
"five_second_break",


# Sentence 1
"sentence_1_narrator_explanation",
"one_second_break",
"narrator_navigation_phrases_7", #listen
"one_second_break",
"sentence_1_target",
"narrator_repetition_phrases_0_0",

# Chunk 1
"sentence_1_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_0_1",
"sentence_1_split_sentence_0_target",
"five_second_break",
"sentence_1_split_sentence_0_target",
"five_second_break",
"narrator_navigation_phrases_11", #It means
"sentence_1_split_sentence_0_native",
"one_second_break",
"sentence_1_split_sentence_0_narrator_fun_fact",
"narrator_repetition_phrases_4",
"sentence_1_split_sentence_0_target",
"five_second_break",
"sentence_1_split_sentence_0_target",
"five_second_break",
"sentence_1_split_sentence_0_target_0",
"five_second_break",
"sentence_1_split_sentence_0_target_0",
"five_second_break",
"sentence_1_split_sentence_0_target_1",
"five_second_break",
"sentence_1_split_sentence_0_target_1",
"five_second_break",
"sentence_1_split_sentence_0_target",
"five_second_break",

# Chunk 2
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_1_split_sentence_1_native",
"one_second_break",
"sentence_1_split_sentence_1_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_1_split_sentence_1_target",
"five_second_break",
"sentence_1_split_sentence_1_target",
"five_second_break",
"sentence_1_split_sentence_1_narrator_fun_fact",
"one_second_break",
"sentence_1_split_sentence_1_target",
"five_second_break",
"sentence_1_split_sentence_1_target",
"five_second_break",
"sentence_1_split_sentence_1_target_0",
"five_second_break",
"sentence_1_split_sentence_1_target_0",
"five_second_break",
"sentence_1_split_sentence_1_target",
"five_second_break",

# Chunk 3
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_1_split_sentence_2_native",
"one_second_break",
"sentence_1_split_sentence_2_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_1_split_sentence_2_target",
"five_second_break",
"sentence_1_split_sentence_2_target",
"five_second_break",
"sentence_1_split_sentence_2_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_1_split_sentence_2_target",
"five_second_break",
"sentence_1_split_sentence_2_target",
"five_second_break",
"sentence_1_split_sentence_2_target_0",
"five_second_break",
"sentence_1_split_sentence_2_target_0",
"five_second_break",
"sentence_1_split_sentence_2_target",

# Chunk 4
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_0_split_sentence_3_native",
"one_second_break",
"sentence_0_split_sentence_3_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break","five_second_break",

#Remember part:
"narrator_navigation_phrases_8_0", # Do you remember how to say...
"sentence_1_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_3_1", # Give it a try
"five_second_break",
"sentence_1_split_sentence_0_target",
"five_second_break",
"sentence_1_split_sentence_0_target",
"five_second_break",

# Wrap up
"narrator_navigation_phrases_10", #listen
"one_second_break",
"sentence_1_target",
"five_second_break",
"sentence_1_target",
"five_second_break",




# Sentence 2
"sentence_2_narrator_explanation",
"one_second_break",
"narrator_navigation_phrases_7", #listen
"one_second_break",
"sentence_2_target",
"narrator_repetition_phrases_0_0",

# Chunk 1
"sentence_2_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_0_1",
"sentence_2_split_sentence_0_target",
"five_second_break",
"sentence_2_split_sentence_0_target",
"five_second_break",
"narrator_navigation_phrases_11", #It means
"sentence_2_split_sentence_0_native",
"one_second_break",
"sentence_2_split_sentence_0_narrator_fun_fact",
"narrator_repetition_phrases_4",
"sentence_2_split_sentence_0_target",
"five_second_break",
"sentence_2_split_sentence_0_target",
"five_second_break",
"sentence_2_split_sentence_0_target_0",
"five_second_break",
"sentence_2_split_sentence_0_target_0",
"five_second_break",
"sentence_2_split_sentence_0_target_1",
"five_second_break",
"sentence_2_split_sentence_0_target_1",
"five_second_break",
"sentence_2_split_sentence_0_target",
"five_second_break",

# Chunk 2
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_2_split_sentence_1_native",
"one_second_break",
"sentence_2_split_sentence_1_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_2_split_sentence_1_target",
"five_second_break",
"sentence_2_split_sentence_1_target",
"five_second_break",
"sentence_2_split_sentence_1_narrator_fun_fact",
"one_second_break",
"sentence_2_split_sentence_1_target",
"five_second_break",
"sentence_2_split_sentence_1_target",
"five_second_break",
"sentence_2_split_sentence_1_target_0",
"five_second_break",
"sentence_2_split_sentence_1_target_0",
"five_second_break",
"sentence_2_split_sentence_1_target",
"five_second_break",

# Chunk 3
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_2_split_sentence_2_native",
"one_second_break",
"sentence_2_split_sentence_2_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_2_split_sentence_2_target",
"five_second_break",
"sentence_2_split_sentence_2_target",
"five_second_break",
"sentence_2_split_sentence_2_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_2_split_sentence_2_target",
"five_second_break",
"sentence_2_split_sentence_2_target",
"five_second_break",
"sentence_2_split_sentence_2_target_0",
"five_second_break",
"sentence_2_split_sentence_2_target_0",
"five_second_break",
"sentence_2_split_sentence_2_target",
"five_second_break",

# Chunk 4
"narrator_repetition_phrases_0_0", # Listen to how they say:
"one_second_break",
"sentence_0_split_sentence_3_native",
"one_second_break",
"sentence_0_split_sentence_3_target",
"one_second_break",
"narrator_repetition_phrases_4",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_narrator_fun_fact",
"narrator_repetition_phrases_8_0",
"one_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target_0",
"five_second_break",
"sentence_0_split_sentence_3_target",
"five_second_break",

#Remember part:
"narrator_navigation_phrases_8_0", # Do you remember how to say...
"sentence_2_split_sentence_0_native",
"one_second_break",
"narrator_repetition_phrases_3_1", # Give it a try
"five_second_break",
"sentence_2_split_sentence_0_target",
"five_second_break",
"sentence_2_split_sentence_0_target",
"five_second_break",

# Wrap up
"narrator_navigation_phrases_10", #listen
"one_second_break",
"sentence_2_target",
"five_second_break",
"sentence_2_target",
"five_second_break",

"narrator_closing_phrases_3"






# "narrator_navigation_phrases_9", #means
# "sentence_0_split_sentence_2_native",
# "one_second_break",
# "narrator_navigation_phrases_10", #listen to the full sentence
# "one_second_break",
# "sentence_0_target",
# "five_second_break",
# "sentence_0_target",
# "five_second_break",
# "navigation_phrases_0", #listen to the next sentence
# "sentence_1_narrator_explanation",
# "sentence_1_target",
# "narrator_repetition_phrases_0_0",
# "sentence_1_split_sentence_0_native",
# "narrator_repetition_phrases_0_1",
# "sentence_1_split_sentence_0_target",
# "five_second_break",
# "sentence_1_split_sentence_0_target",
# "narrator_navigation_phrases_9", #means
# "sentence_1_split_sentence_0_native",
# "one_second_break",
# "sentence_1_split_sentence_0_narrator_fun_fact",
# "narrator_repetition_phrases_14_0",
# "sentence_1_split_sentence_0_target",
# "narrator_repetition_phrases_14_1",
# "five_second_break",
# "sentence_1_target",
# "sentence_1_split_sentence_1_target",
# "narrator_navigation_phrases_9", #means
# "sentence_1_split_sentence_1_native",
# "one_second_break",
# "narrator_repetition_phrases_4",
# "sentence_1_split_sentence_1_target",
# "one_second_break",
# "sentence_1_split_sentence_1_target",
# "five_second_break",
# "sentence_1_split_sentence_1_target",
# "narrator_repetition_phrases_24_0",
# "sentence_1_split_sentence_1_native",
# "narrator_repetition_phrases_24_1",
# "five_second_break",
# "sentence_1_split_sentence_1_target",
# "sentence_1_split_sentence_1_narrator_fun_fact",
# "sentence_1_target",
# "one_second_break",
# "narrator_repetition_phrases_9_0",
# "sentence_1_split_sentence_2_target",
# "narrator_repetition_phrases_9_1",
# "sentence_1_split_sentence_2_target",
# "five_second_break",
# "sentence_1_split_sentence_2_target",
# "narrator_navigation_phrases_9", #means
# "sentence_1_split_sentence_2_native",
# "one_second_break",
# "sentence_1_split_sentence_2_narrator_fun_fact",
# "sentence_1_target",
# "navigation_phrases_0", #listen to the next sentence
# "sentence_2_narrator_explanation",
# "sentence_2_target",
# "narrator_repetition_phrases_0_0",
# "sentence_2_split_sentence_0_native",
# "narrator_repetition_phrases_0_1",
# "sentence_2_split_sentence_0_target",
# "five_second_break",
# "sentence_2_split_sentence_0_target",
# "narrator_navigation_phrases_9", #means
# "sentence_2_split_sentence_0_native",
# "one_second_break",
# "sentence_2_split_sentence_0_narrator_fun_fact",
# "narrator_repetition_phrases_14_0",
# "sentence_2_split_sentence_0_target",
# "narrator_repetition_phrases_14_1",
# "five_second_break",
# "sentence_2_target",
# "sentence_2_split_sentence_1_target",
# "narrator_navigation_phrases_9", #means
# "sentence_2_split_sentence_1_native",
# "one_second_break",
# "narrator_repetition_phrases_4",
# "sentence_2_split_sentence_1_target",
# "one_second_break",
# "sentence_2_split_sentence_1_target",
# "five_second_break",
# "sentence_2_split_sentence_1_target",
# "narrator_repetition_phrases_24_0",
# "sentence_2_split_sentence_1_native",
# "narrator_repetition_phrases_24_1",
# "five_second_break",
# "sentence_2_split_sentence_1_target",
# "sentence_2_split_sentence_1_narrator_fun_fact",
# "sentence_2_target",
# "one_second_break",
# "narrator_repetition_phrases_9_0",
# "sentence_2_split_sentence_2_target",
# "narrator_repetition_phrases_9_1",
# "sentence_2_split_sentence_2_target",
# "five_second_break"
]
