LANGUAGE_NAMES = {
    "hi-IN": "Hindi",
    "id-ID": "Indonesian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "kn-IN": "Kannada",
    "ko-KR": "Korean",
    "ml-IN": "Malayalam",
    "ms-MY": "Malay",
    "ne-NP": "Nepali",
    "nb-NO": "Norwegian",
    "pa-IN": "Punjabi",
    "pl-PL": "Polish",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "ru-RU": "Russian",
    "sv-SE": "Swedish",
    "ta-IN": "Tamil",
    "tr-TR": "Turkish",
    "vi-VN": "Vietnamese"
}