const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["café", "chá", "leite", "açúcar", "chávena", "pedido", "ementa", "mesa", "barista", "recibo", "troco", "para levar", "gelado", "quente", "colher", "guardanapo", "natas", "expresso", "latte", "gorjeta"]
  },
  {
    "name": "Weather Talk",
    "words": ["solarengo", "chuvoso", "nublado", "ventoso", "tempestuoso", "neve", "quente", "frio", "ameno", "fresco", "previsão", "guarda-chuva", "casaco", "temperatura", "graus", "estação", "húmido", "seco"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "carrinho",
      "cesto",
      "corredor",
      "caixa",
      "caixa",
      "recibo",
      "saco",
      "frutas",
      "legumes",
      "pão",
      "lacticínios",
      "carne",
      "congelado",
      "enlatado",
      "prateleira",
      "preço",
      "promoção",
      "código de barras",
      "dinheiro",
      "cartão"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["mapa", "rua", "caminho", "avenida", "esquerda", "direita", "reto", "esquina", "quarteirão", "semáforo", "cruzamento", "virar", "perto", "longe", "atrás", "frente", "ao lado", "entre", "em frente", "placa"]
  },
  {
    "name": "Essential Conversations",
    "words": ["olá", "oi", "como está", "bem", "obrigado", "você", "tempo", "bom", "mau", "ocupado", "cansado", "fim de semana", "planos", "aproveitar", "hoje", "amanhã", "ontem", "agradável", "encontrar", "novamente"]
  },
  {
    "name": "At the Airport",
    "words": [
      "cartão de embarque",
      "passaporte",
      "bagagem",
      "check-in",
      "segurança",
      "porta de embarque",
      "voo",
      "atraso",
      "partida",
      "chegada",
      "terminal",
      "levantamento de bagagem",
      "alfândega",
      "bilhete",
      "lugar",
      "embarque",
      "bagagem de mão",
      "carrinho de bebé",
      "visto",
      "duty-free"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "ementa",
      "empregado de mesa",
      "reserva",
      "pedido",
      "entrada",
      "prato principal",
      "sobremesa",
      "conta",
      "gorjeta",
      "bebida",
      "água",
      "vinho",
      "cerveja",
      "garfo",
      "faca",
      "colher",
      "prato",
      "copo",
      "guardanapo",
      "especialidade"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "receção",
      "check-in",
      "check-out",
      "quarto",
      "chave",
      "reserva",
      "bagagem",
      "elevador",
      "pequeno-almoço",
      "wi-fi",
      "chuveiro",
      "toalha",
      "cama",
      "almofada",
      "cobertor",
      "ar condicionado",
      "lavandaria",
      "serviço",
      "cofre",
      "vista"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "consulta",
      "médico",
      "enfermeiro",
      "sintomas",
      "dor",
      "febre",
      "tosse",
      "dor de cabeça",
      "receita",
      "medicamento",
      "farmácia",
      "alergia",
      "pressão arterial",
      "temperatura",
      "estetoscópio",
      "penso",
      "injeção",
      "raio-x",
      "diagnóstico",
      "tratamento"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "autocarro",
      "comboio",
      "metro",
      "bilhete",
      "estação",
      "paragem",
      "horário",
      "mapa",
      "rota",
      "plataforma",
      "tarifa",
      "transbordo",
      "passageiro",
      "condutor",
      "revisor",
      "atraso",
      "saída",
      "entrada",
      "lugar sentado",
      "em pé"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": ["camisa", "calças", "vestido", "sapatos", "tamanho", "cor", "preço", "promoção", "cabine de prova", "caixa", "recibo", "saco", "casaco", "camisola", "saia", "chapéu", "meias", "jeans", "cinto", "desconto"]
  },
  {
    "name": "At the Gym",
    "words": [
      "passadeira",
      "pesos",
      "yoga",
      "alongamento",
      "treinador pessoal",
      "inscrição",
      "cacifo",
      "chuveiro",
      "toalha",
      "garrafa de água",
      "exercício",
      "cardio",
      "força",
      "repetições",
      "séries",
      "aquecimento",
      "arrefecimento",
      "halteres",
      "barra",
      "máquina"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "conta",
      "levantamento",
      "depósito",
      "empréstimo",
      "juros",
      "cartão de crédito",
      "cartão de débito",
      "multibanco",
      "caixa de banco",
      "saldo",
      "moeda",
      "câmbio",
      "cheque",
      "poupança",
      "investimento",
      "palavra-passe",
      "pin",
      "extrato",
      "taxa",
      "transferência"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "pacote",
      "carta",
      "selo",
      "envelope",
      "endereço",
      "postal",
      "encomenda",
      "entrega",
      "rastreamento",
      "caixa de correio",
      "remetente",
      "destinatário",
      "peso",
      "tamanho",
      "prioridade",
      "expresso",
      "correio aéreo",
      "alfândega",
      "taxa",
      "recibo"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "medicamento",
      "receita",
      "analgésico",
      "penso",
      "vitaminas",
      "xarope para a tosse",
      "alergia",
      "creme",
      "pomada",
      "pílula",
      "comprimido",
      "cápsula",
      "farmacêutico",
      "dosagem",
      "efeitos secundários",
      "reposição",
      "antibiótico",
      "termómetro",
      "máscara",
      "desinfetante"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "banco",
      "árvore",
      "relva",
      "caminho",
      "parque infantil",
      "fonte",
      "cão",
      "piquenique",
      "bicicleta",
      "corrida",
      "flores",
      "lago",
      "pato",
      "sombra",
      "sol",
      "crianças",
      "baloiço",
      "escorrega",
      "contentor do lixo",
      "estátua"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "areia",
      "ondas",
      "sol",
      "chapéu de sol",
      "toalha",
      "fato de banho",
      "protetor solar",
      "óculos de sol",
      "chapéu",
      "conchas",
      "gaivota",
      "mar",
      "maré",
      "surf",
      "prancha",
      "mergulho",
      "máscara",
      "barbatanas",
      "bola de praia",
      "gelado"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "livro",
      "prateleira",
      "catálogo",
      "requisitar",
      "devolver",
      "data de devolução",
      "bibliotecário",
      "estudar",
      "silêncio",
      "secretária",
      "cadeira",
      "computador",
      "internet",
      "revista",
      "jornal",
      "ficção",
      "não ficção",
      "referência",
      "empréstimo",
      "cartão"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "bilhete",
      "filme",
      "pipocas",
      "bebida",
      "lugar",
      "ecrã",
      "trailer",
      "género",
      "terror",
      "comédia",
      "ação",
      "drama",
      "romance",
      "realizador",
      "ator",
      "atriz",
      "legendas",
      "3d",
      "horário da sessão",
      "concessão"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "corte de cabelo",
      "champô",
      "amaciador",
      "cabeleireiro",
      "tesoura",
      "pente",
      "secador",
      "coloração",
      "madeixas",
      "aparar",
      "franja",
      "caracóis",
      "alisamento",
      "marcação",
      "espelho",
      "cadeira",
      "capa",
      "navalha",
      "gel",
      "spray"
    ]
  }
];
