const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["café", "té", "leche", "azúcar", "taza", "pedido", "menú", "mesa", "barista", "recibo", "cambio", "para llevar", "helado", "caliente", "cuchara", "servilleta", "crema", "espresso", "latte", "propina"]
  },
  {
    "name": "Weather Talk",
    "words": ["soleado", "lluvioso", "nublado", "ventoso", "tormentoso", "nieve", "calor", "frío", "templado", "fresco", "pronóstico", "paraguas", "abrigo", "temperatura", "grados", "estación", "húmedo", "seco"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "carrito",
      "cesta",
      "pasillo",
      "caja",
      "cajero",
      "recibo",
      "bolsa",
      "fruta",
      "verduras",
      "pan",
      "lácteos",
      "carne",
      "congelado",
      "enlatado",
      "estante",
      "precio",
      "oferta",
      "código de barras",
      "efectivo",
      "tarjeta"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["mapa", "calle", "carretera", "avenida", "izquierda", "derecha", "recto", "esquina", "manzana", "semáforo", "cruce", "girar", "cerca", "lejos", "detrás", "delante", "al lado", "entre", "enfrente", "señal"]
  },
  {
    "name": "Making Small Talk",
    "words": ["hola", "qué tal", "bien", "gracias", "tú", "tiempo", "bien", "mal", "ocupado", "cansado", "fin de semana", "planes", "disfrutar", "hoy", "mañana", "ayer", "agradable", "conocer", "otra vez"]
  },
  {
    "name": "At the Airport",
    "words": [
      "tarjeta de embarque",
      "pasaporte",
      "equipaje",
      "facturación",
      "seguridad",
      "puerta de embarque",
      "vuelo",
      "retraso",
      "salida",
      "llegada",
      "terminal",
      "recogida de equipajes",
      "aduana",
      "billete",
      "asiento",
      "embarque",
      "equipaje de mano",
      "cochecito de bebé",
      "visa",
      "libre de impuestos"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menú",
      "camarero",
      "reserva",
      "pedido",
      "aperitivo",
      "plato principal",
      "postre",
      "cuenta",
      "propina",
      "bebida",
      "agua",
      "vino",
      "cerveza",
      "tenedor",
      "cuchillo",
      "cuchara",
      "plato",
      "vaso",
      "servilleta",
      "especialidad"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "recepción",
      "registro de entrada",
      "registro de salida",
      "habitación",
      "llave",
      "reserva",
      "equipaje",
      "ascensor",
      "desayuno",
      "wi-fi",
      "ducha",
      "toalla",
      "cama",
      "almohada",
      "manta",
      "aire acondicionado",
      "lavandería",
      "servicio",
      "caja fuerte",
      "vista"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "cita",
      "médico",
      "enfermera",
      "síntomas",
      "dolor",
      "fiebre",
      "tos",
      "dolor de cabeza",
      "receta",
      "medicina",
      "farmacia",
      "alergia",
      "presión arterial",
      "temperatura",
      "estetoscopio",
      "vendaje",
      "inyección",
      "radiografía",
      "diagnóstico",
      "tratamiento"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "autobús",
      "tren",
      "metro",
      "billete",
      "estación",
      "parada",
      "horario",
      "mapa",
      "ruta",
      "andén",
      "tarifa",
      "transbordo",
      "pasajero",
      "conductor",
      "revisor",
      "retraso",
      "salida",
      "entrada",
      "asiento",
      "de pie"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "camisa",
      "pantalones",
      "vestido",
      "zapatos",
      "talla",
      "color",
      "precio",
      "oferta",
      "probador",
      "cajero",
      "recibo",
      "bolsa",
      "chaqueta",
      "jersey",
      "falda",
      "sombrero",
      "calcetines",
      "vaqueros",
      "cinturón",
      "descuento"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "cinta de correr",
      "pesas",
      "yoga",
      "estiramientos",
      "entrenador",
      "membresía",
      "taquilla",
      "ducha",
      "toalla",
      "botella de agua",
      "ejercicio",
      "cardio",
      "fuerza",
      "repeticiones",
      "series",
      "calentamiento",
      "enfriamiento",
      "mancuerna",
      "barra",
      "máquina"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "cuenta",
      "retirada",
      "depósito",
      "préstamo",
      "interés",
      "tarjeta de crédito",
      "tarjeta de débito",
      "cajero automático",
      "cajero",
      "saldo",
      "moneda",
      "cambio",
      "cheque",
      "ahorros",
      "inversión",
      "contraseña",
      "pin",
      "extracto",
      "comisión",
      "transferencia"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "paquete",
      "carta",
      "sello",
      "sobre",
      "dirección",
      "postal",
      "paquete",
      "entrega",
      "seguimiento",
      "buzón",
      "remitente",
      "destinatario",
      "peso",
      "tamaño",
      "prioritario",
      "exprés",
      "correo aéreo",
      "aduana",
      "comisión",
      "recibo"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "medicina",
      "receta",
      "analgésico",
      "vendaje",
      "vitaminas",
      "jarabe para la tos",
      "alergia",
      "crema",
      "ungüento",
      "pastilla",
      "tableta",
      "cápsula",
      "farmacéutico",
      "dosis",
      "efectos secundarios",
      "recarga",
      "antibiótico",
      "termómetro",
      "mascarilla",
      "desinfectante"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "banco",
      "árbol",
      "césped",
      "sendero",
      "parque infantil",
      "fuente",
      "perro",
      "picnic",
      "bicicleta",
      "correr",
      "flores",
      "estanque",
      "pato",
      "sombra",
      "sol",
      "niños",
      "columpio",
      "tobogán",
      "papelera",
      "estatua"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "arena",
      "olas",
      "sol",
      "sombrilla",
      "toalla",
      "traje de baño",
      "protector solar",
      "gafas de sol",
      "sombrero",
      "conchas",
      "gaviota",
      "océano",
      "marea",
      "surf",
      "tabla",
      "esnórquel",
      "máscara",
      "aletas",
      "pelota de playa",
      "helado"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "libro",
      "estantería",
      "catálogo",
      "prestar",
      "devolver",
      "fecha de vencimiento",
      "bibliotecario",
      "estudiar",
      "silencio",
      "escritorio",
      "silla",
      "ordenador",
      "internet",
      "revista",
      "periódico",
      "ficción",
      "no ficción",
      "referencia",
      "préstamo",
      "tarjeta"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "entrada",
      "película",
      "palomitas",
      "bebida",
      "asiento",
      "pantalla",
      "tráiler",
      "género",
      "terror",
      "comedia",
      "acción",
      "drama",
      "romance",
      "director",
      "actor",
      "actriz",
      "subtítulos",
      "3d",
      "horario de proyección",
      "concesión"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "corte de pelo",
      "champú",
      "acondicionador",
      "estilista",
      "tijeras",
      "peine",
      "secado",
      "color",
      "mechas",
      "recorte",
      "flequillo",
      "rizos",
      "alisado",
      "cita",
      "espejo",
      "silla",
      "capa",
      "navaja",
      "gel",
      "spray"
    ]
  }
];
