const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["cà phê", "trà", "sữa", "đường", "tách", "đặt hàng", "thực đơn", "bàn", "nhân viên pha chế", "hóa đơn", "tiền thừa", "mang đi", "đá", "nóng", "thìa", "khăn giấy", "kem", "espresso", "latte", "tiền boa"]
  },
  {
    "name": "Weather Talk",
    "words": ["nắng", "mưa", "nhiều mây", "gió", "bão", "tuyết", "nóng", "lạnh", "ấm áp", "mát mẻ", "dự báo thời tiết", "ô", "áo khoác", "nhiệt độ", "độ", "mùa", "ẩm ướt", "khô ráo"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "xe đẩy",
      "giỏ",
      "lối đi",
      "quầy thanh toán",
      "nhân viên thu ngân",
      "hóa đơn",
      "túi",
      "trái cây",
      "rau củ",
      "bánh mì",
      "sản phẩm từ sữa",
      "thịt",
      "đông lạnh",
      "đóng hộp",
      "kệ",
      "giá",
      "giảm giá",
      "mã vạch",
      "tiền mặt",
      "thẻ"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["bản đồ", "đường", "lối đi", "đại lộ", "trái", "phải", "thẳng", "góc", "khối nhà", "đèn giao thông", "ngã tư", "rẽ", "gần", "xa", "phía sau", "phía trước", "bên cạnh", "giữa", "đối diện", "biển báo"]
  },
  {
    "name": "Essential Conversations",
    "words": [
      "xin chào",
      "chào",
      "bạn khỏe không",
      "khỏe",
      "cảm ơn",
      "bạn",
      "thời tiết",
      "tốt",
      "xấu",
      "bận rộn",
      "mệt mỏi",
      "cuối tuần",
      "kế hoạch",
      "tận hưởng",
      "hôm nay",
      "ngày mai",
      "hôm qua",
      "tuyệt vời",
      "gặp gỡ",
      "lại"
    ]
  },
  {
    "name": "At the Airport",
    "words": [
      "thẻ lên máy bay",
      "hộ chiếu",
      "hành lý",
      "làm thủ tục",
      "an ninh",
      "cổng",
      "chuyến bay",
      "trễ",
      "khởi hành",
      "đến",
      "nhà ga",
      "khu vực nhận hành lý",
      "hải quan",
      "vé",
      "chỗ ngồi",
      "lên máy bay",
      "hành lý xách tay",
      "xe đẩy trẻ em",
      "visa",
      "miễn thuế"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "thực đơn",
      "bồi bàn",
      "đặt chỗ",
      "đặt hàng",
      "món khai vị",
      "món chính",
      "món tráng miệng",
      "hóa đơn",
      "tiền boa",
      "đồ uống",
      "nước",
      "rượu vang",
      "bia",
      "nĩa",
      "dao",
      "thìa",
      "đĩa",
      "ly",
      "khăn ăn",
      "món đặc biệt"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "quầy lễ tân",
      "nhận phòng",
      "trả phòng",
      "phòng",
      "chìa khóa",
      "đặt phòng",
      "hành lý",
      "thang máy",
      "bữa sáng",
      "wi-fi",
      "vòi hoa sen",
      "khăn tắm",
      "giường",
      "gối",
      "chăn",
      "điều hòa không khí",
      "giặt ủi",
      "dịch vụ",
      "két an toàn",
      "tầm nhìn"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "cuộc hẹn",
      "bác sĩ",
      "y tá",
      "triệu chứng",
      "đau",
      "sốt",
      "ho",
      "đau đầu",
      "toa thuốc",
      "thuốc",
      "nhà thuốc",
      "dị ứng",
      "huyết áp",
      "nhiệt độ",
      "ống nghe",
      "băng dán",
      "tiêm",
      "x-quang",
      "chẩn đoán",
      "điều trị"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "xe buýt",
      "tàu hỏa",
      "tàu điện ngầm",
      "vé",
      "ga",
      "trạm dừng",
      "lịch trình",
      "bản đồ",
      "tuyến đường",
      "sân ga",
      "giá vé",
      "chuyển tuyến",
      "hành khách",
      "tài xế",
      "người soát vé",
      "trễ giờ",
      "lối ra",
      "lối vào",
      "chỗ ngồi",
      "đứng"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "áo sơ mi",
      "quần",
      "váy",
      "giày",
      "kích cỡ",
      "màu sắc",
      "giá",
      "giảm giá",
      "phòng thử đồ",
      "nhân viên thu ngân",
      "hóa đơn",
      "túi",
      "áo khoác",
      "áo len",
      "váy",
      "mũ",
      "vớ",
      "quần jean",
      "thắt lưng",
      "giảm giá"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "máy chạy bộ",
      "tạ",
      "yoga",
      "kéo giãn",
      "huấn luyện viên",
      "thẻ thành viên",
      "tủ khóa",
      "vòi hoa sen",
      "khăn tắm",
      "chai nước",
      "tập thể dục",
      "cardio",
      "sức mạnh",
      "lần lặp lại",
      "hiệp",
      "khởi động",
      "hạ nhiệt",
      "tạ tay",
      "tạ đòn",
      "máy tập"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "tài khoản",
      "rút tiền",
      "gửi tiền",
      "khoản vay",
      "lãi suất",
      "thẻ tín dụng",
      "thẻ ghi nợ",
      "máy atm",
      "nhân viên ngân hàng",
      "số dư",
      "tiền tệ",
      "đổi tiền",
      "séc",
      "tiết kiệm",
      "đầu tư",
      "mật khẩu",
      "mã pin",
      "bảng sao kê",
      "phí",
      "chuyển khoản"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "bưu kiện",
      "thư",
      "tem",
      "phong bì",
      "địa chỉ",
      "bưu thiếp",
      "bưu kiện",
      "giao hàng",
      "theo dõi",
      "hộp thư",
      "người gửi",
      "người nhận",
      "trọng lượng",
      "kích thước",
      "ưu tiên",
      "chuyển phát nhanh",
      "thư hàng không",
      "hải quan",
      "phí",
      "biên lai"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "thuốc",
      "toa thuốc",
      "thuốc giảm đau",
      "băng dán",
      "vitamin",
      "siro ho",
      "dị ứng",
      "kem",
      "thuốc mỡ",
      "viên thuốc",
      "viên nén",
      "viên nang",
      "dược sĩ",
      "liều dùng",
      "tác dụng phụ",
      "nạp lại",
      "kháng sinh",
      "nhiệt kế",
      "khẩu trang",
      "nước rửa tay"
    ]
  },
  {
    "name": "At the Park",
    "words": ["ghế dài", "cây", "cỏ", "lối đi", "sân chơi", "đài phun nước", "chó", "dã ngoại", "xe đạp", "chạy bộ", "hoa", "ao", "vịt", "bóng râm", "mặt trời", "trẻ em", "đu", "cầu trượt", "thùng rác", "tượng"]
  },
  {
    "name": "At the Beach",
    "words": [
      "cát",
      "sóng",
      "mặt trời",
      "ô",
      "khăn tắm",
      "đồ bơi",
      "kem chống nắng",
      "kính râm",
      "mũ",
      "vỏ sò",
      "mòng biển",
      "biển",
      "thủy triều",
      "lướt sóng",
      "ván",
      "lặn biển",
      "mặt nạ",
      "chân vịt",
      "bóng bãi biển",
      "kem"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "sách",
      "kệ sách",
      "danh mục",
      "mượn",
      "trả lại",
      "ngày đến hạn",
      "thủ thư",
      "học tập",
      "yên tĩnh",
      "bàn",
      "ghế",
      "máy tính",
      "internet",
      "tạp chí",
      "báo",
      "tiểu thuyết",
      "phi tiểu thuyết",
      "tài liệu tham khảo",
      "khoản vay",
      "thẻ"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "vé",
      "phim",
      "bắp rang bơ",
      "đồ uống",
      "chỗ ngồi",
      "màn hình",
      "đoạn giới thiệu",
      "thể loại",
      "kinh dị",
      "hài",
      "hành động",
      "kịch",
      "lãng mạn",
      "đạo diễn",
      "diễn viên",
      "nữ diễn viên",
      "phụ đề",
      "3d",
      "giờ chiếu",
      "nhượng quyền"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": ["cắt tóc", "dầu gội", "dầu xả", "thợ làm tóc", "kéo", "lược", "sấy khô", "nhuộm", "highlight", "cắt tỉa", "tóc mái", "xoăn", "duỗi thẳng", "cuộc hẹn", "gương", "ghế", "áo choàng", "dao cạo", "gel", "xịt"]
  }
];
