const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["café", "té", "leche", "azúcar", "taza", "orden", "menú", "mesa", "barista", "ticket", "cambio", "para llevar", "helado", "caliente", "cuchara", "servilleta", "crema", "espresso", "latte", "propina"]
  },
  {
    "name": "Weather Talk",
    "words": ["soleado", "lluvioso", "nublado", "ventoso", "tormentoso", "nieve", "calor", "frío", "tibio", "fresco", "pronóstico", "paraguas", "abrigo", "temperatura", "grados", "estación", "húmedo", "seco"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "carrito",
      "canasta",
      "pasillo",
      "caja",
      "cajero",
      "ticket",
      "bolsa",
      "fruta",
      "verduras",
      "pan",
      "lácteos",
      "carne",
      "congelado",
      "enlatado",
      "estante",
      "precio",
      "oferta",
      "código de barras",
      "efectivo",
      "tarjeta"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": [
      "mapa",
      "calle",
      "avenida",
      "carretera",
      "izquierda",
      "derecha",
      "derecho",
      "esquina",
      "cuadra",
      "semáforo",
      "crucero",
      "dar vuelta",
      "cerca",
      "lejos",
      "detrás",
      "enfrente",
      "al lado",
      "entre",
      "opuesto",
      "letrero"
    ]
  },
  {
    "name": "Making Small Talk",
    "words": ["hola", "qué onda", "bien", "gracias", "tú", "clima", "bien", "mal", "ocupado", "cansado", "fin de semana", "planes", "disfrutar", "hoy", "mañana", "ayer", "chido", "conocer", "otra vez"]
  },
  {
    "name": "At the Airport",
    "words": [
      "pase de abordar",
      "pasaporte",
      "equipaje",
      "check-in",
      "seguridad",
      "puerta",
      "vuelo",
      "retraso",
      "salida",
      "llegada",
      "terminal",
      "reclamo de equipaje",
      "aduana",
      "boleto",
      "asiento",
      "abordar",
      "equipaje de mano",
      "carriola",
      "visa",
      "libre de impuestos"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menú",
      "mesero",
      "reservación",
      "orden",
      "entrada",
      "plato fuerte",
      "postre",
      "cuenta",
      "propina",
      "bebida",
      "agua",
      "vino",
      "cerveza",
      "tenedor",
      "cuchillo",
      "cuchara",
      "plato",
      "vaso",
      "servilleta",
      "especialidad"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "recepción",
      "check-in",
      "check-out",
      "habitación",
      "llave",
      "reservación",
      "equipaje",
      "elevador",
      "desayuno",
      "wi-fi",
      "regadera",
      "toalla",
      "cama",
      "almohada",
      "cobija",
      "aire acondicionado",
      "lavandería",
      "servicio",
      "caja fuerte",
      "vista"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "cita",
      "doctor",
      "enfermera",
      "síntomas",
      "dolor",
      "fiebre",
      "tos",
      "dolor de cabeza",
      "receta",
      "medicina",
      "farmacia",
      "alergia",
      "presión arterial",
      "temperatura",
      "estetoscopio",
      "venda",
      "inyección",
      "radiografía",
      "diagnóstico",
      "tratamiento"
    ]
  },
  {
    "name": "Public Transportation",
    "words": ["autobús", "tren", "metro", "boleto", "estación", "parada", "horario", "mapa", "ruta", "andén", "tarifa", "transbordo", "pasajero", "chofer", "cobrador", "retraso", "salida", "entrada", "asiento", "parado"]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "camisa",
      "pantalones",
      "vestido",
      "zapatos",
      "talla",
      "color",
      "precio",
      "oferta",
      "probador",
      "cajero",
      "ticket",
      "bolsa",
      "chamarra",
      "suéter",
      "falda",
      "sombrero",
      "calcetines",
      "jeans",
      "cinturón",
      "descuento"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "caminadora",
      "pesas",
      "yoga",
      "estiramientos",
      "entrenador",
      "membresía",
      "casillero",
      "regadera",
      "toalla",
      "botella de agua",
      "ejercicio",
      "cardio",
      "fuerza",
      "repeticiones",
      "series",
      "calentamiento",
      "enfriamiento",
      "mancuerna",
      "barra",
      "máquina"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "cuenta",
      "retiro",
      "depósito",
      "préstamo",
      "interés",
      "tarjeta de crédito",
      "tarjeta de débito",
      "cajero automático",
      "cajero",
      "saldo",
      "moneda",
      "cambio",
      "cheque",
      "ahorros",
      "inversión",
      "contraseña",
      "pin",
      "estado de cuenta",
      "comisión",
      "transferencia"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "paquete",
      "carta",
      "estampilla",
      "sobre",
      "dirección",
      "postal",
      "paquete",
      "entrega",
      "rastreo",
      "buzón",
      "remitente",
      "destinatario",
      "peso",
      "tamaño",
      "prioritario",
      "exprés",
      "correo aéreo",
      "aduana",
      "comisión",
      "ticket"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "medicina",
      "receta",
      "analgésico",
      "venda",
      "vitaminas",
      "jarabe para la tos",
      "alergia",
      "crema",
      "ungüento",
      "pastilla",
      "tableta",
      "cápsula",
      "farmacéutico",
      "dosis",
      "efectos secundarios",
      "resurtir",
      "antibiótico",
      "termómetro",
      "cubrebocas",
      "gel antibacterial"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "banca",
      "árbol",
      "pasto",
      "sendero",
      "parque infantil",
      "fuente",
      "perro",
      "picnic",
      "bicicleta",
      "correr",
      "flores",
      "estanque",
      "pato",
      "sombra",
      "sol",
      "niños",
      "columpio",
      "resbaladilla",
      "bote de basura",
      "estatua"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "arena",
      "olas",
      "sol",
      "sombrilla",
      "toalla",
      "traje de baño",
      "bloqueador solar",
      "lentes de sol",
      "sombrero",
      "conchas",
      "gaviota",
      "océano",
      "marea",
      "surf",
      "tabla",
      "snorkel",
      "máscara",
      "aletas",
      "pelota de playa",
      "helado"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "libro",
      "estante",
      "catálogo",
      "prestar",
      "regresar",
      "fecha de entrega",
      "bibliotecario",
      "estudiar",
      "silencio",
      "escritorio",
      "silla",
      "computadora",
      "internet",
      "revista",
      "periódico",
      "ficción",
      "no ficción",
      "referencia",
      "préstamo",
      "tarjeta"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "boleto",
      "película",
      "palomitas",
      "refresco",
      "asiento",
      "pantalla",
      "tráiler",
      "género",
      "terror",
      "comedia",
      "acción",
      "drama",
      "romance",
      "director",
      "actor",
      "actriz",
      "subtítulos",
      "3d",
      "horario",
      "dulcería"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "corte de cabello",
      "champú",
      "acondicionador",
      "estilista",
      "tijeras",
      "peine",
      "secado",
      "tinte",
      "luces",
      "recorte",
      "fleco",
      "chinos",
      "alaciado",
      "cita",
      "espejo",
      "silla",
      "capa",
      "navaja",
      "gel",
      "spray"
    ]
  }
];
