const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["kopi", "teh", "susu", "gula", "cangkir", "pesanan", "menu", "meja", "barista", "struk", "uang kembalian", "dibawa pulang", "es", "panas", "sendok", "serbet", "krim", "espresso", "latte", "tip"]
  },
  {
    "name": "Weather Talk",
    "words": ["cerah", "hujan", "berawan", "berangin", "badai", "salju", "panas", "dingin", "hangat", "sejuk", "prakiraan", "payung", "jaket", "suhu", "derajat", "musim", "lembab", "kering"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "kereta dorong",
      "keranjang",
      "lorong",
      "kasir",
      "kasir",
      "struk",
      "tas",
      "buah-buahan",
      "sayuran",
      "roti",
      "produk susu",
      "daging",
      "beku",
      "kalengan",
      "rak",
      "harga",
      "diskon",
      "kode batang",
      "tunai",
      "kartu"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": [
      "peta",
      "jalan",
      "jalan",
      "jalan besar",
      "kiri",
      "kanan",
      "lurus",
      "sudut",
      "blok",
      "lampu lalu lintas",
      "persimpangan",
      "belok",
      "dekat",
      "jauh",
      "belakang",
      "depan",
      "di samping",
      "antara",
      "di seberang",
      "tanda"
    ]
  },
  {
    "name": "Making Small Talk",
    "words": [
      "halo",
      "hai",
      "bagaimana",
      "baik",
      "terima kasih",
      "kamu",
      "cuaca",
      "baik",
      "buruk",
      "sibuk",
      "lelah",
      "akhir pekan",
      "rencana",
      "nikmati",
      "hari ini",
      "besok",
      "kemarin",
      "menyenangkan",
      "bertemu",
      "lagi"
    ]
  },
  {
    "name": "At the Airport",
    "words": [
      "kartu boarding",
      "paspor",
      "bagasi",
      "check-in",
      "keamanan",
      "gerbang",
      "penerbangan",
      "penundaan",
      "keberangkatan",
      "kedatangan",
      "terminal",
      "pengambilan bagasi",
      "bea cukai",
      "tiket",
      "kursi",
      "boarding",
      "kabin",
      "kereta bayi",
      "visa",
      "bebas bea"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menu",
      "pelayan",
      "reservasi",
      "pesanan",
      "makanan pembuka",
      "hidangan utama",
      "hidangan penutup",
      "tagihan",
      "tip",
      "minuman",
      "air",
      "anggur",
      "bir",
      "garpu",
      "pisau",
      "sendok",
      "piring",
      "gelas",
      "serbet",
      "spesial"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "resepsionis",
      "check-in",
      "check-out",
      "kamar",
      "kunci",
      "reservasi",
      "bagasi",
      "lift",
      "sarapan",
      "wi-fi",
      "pancuran",
      "handuk",
      "tempat tidur",
      "bantal",
      "selimut",
      "pendingin ruangan",
      "binatu",
      "layanan",
      "brankas",
      "pemandangan"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "janji temu",
      "dokter",
      "perawat",
      "gejala",
      "sakit",
      "demam",
      "batuk",
      "sakit kepala",
      "resep",
      "obat",
      "apotek",
      "alergi",
      "tekanan darah",
      "suhu",
      "stetoskop",
      "perban",
      "suntikan",
      "x-ray",
      "diagnosis",
      "pengobatan"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "bus",
      "kereta api",
      "metro",
      "tiket",
      "stasiun",
      "halte",
      "jadwal",
      "peta",
      "rute",
      "peron",
      "ongkos",
      "transfer",
      "penumpang",
      "pengemudi",
      "kondektur",
      "penundaan",
      "pintu keluar",
      "pintu masuk",
      "tempat duduk",
      "berdiri"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": ["kemeja", "celana", "gaun", "sepatu", "ukuran", "warna", "harga", "diskon", "kamar pas", "kasir", "struk", "tas", "jaket", "sweater", "rok", "topi", "kaus kaki", "jeans", "ikat pinggang", "potongan harga"]
  },
  {
    "name": "At the Gym",
    "words": [
      "treadmill",
      "beban",
      "yoga",
      "peregangan",
      "pelatih",
      "keanggotaan",
      "loker",
      "pancuran",
      "handuk",
      "botol air",
      "latihan",
      "kardio",
      "kekuatan",
      "repetisi",
      "set",
      "pemanasan",
      "pendinginan",
      "dumbbell",
      "barbel",
      "mesin"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "rekening",
      "penarikan",
      "setoran",
      "pinjaman",
      "bunga",
      "kartu kredit",
      "kartu debit",
      "ATM",
      "teller",
      "saldo",
      "mata uang",
      "penukaran",
      "cek",
      "tabungan",
      "investasi",
      "kata sandi",
      "pin",
      "laporan",
      "biaya",
      "transfer"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "paket",
      "surat",
      "perangko",
      "amplop",
      "alamat",
      "kartu pos",
      "paket",
      "pengiriman",
      "pelacakan",
      "kotak surat",
      "pengirim",
      "penerima",
      "berat",
      "ukuran",
      "prioritas",
      "ekspres",
      "udara",
      "bea cukai",
      "biaya",
      "struk"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "obat",
      "resep",
      "pereda nyeri",
      "perban",
      "vitamin",
      "sirup obat batuk",
      "alergi",
      "krim",
      "salep",
      "pil",
      "tablet",
      "kapsul",
      "apoteker",
      "dosis",
      "efek samping",
      "isi ulang",
      "antibiotik",
      "termometer",
      "masker",
      "pembersih tangan"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "bangku",
      "pohon",
      "rumput",
      "jalan setapak",
      "taman bermain",
      "air mancur",
      "anjing",
      "piknik",
      "sepeda",
      "jogging",
      "bunga",
      "kolam",
      "bebek",
      "bayangan",
      "matahari",
      "anak-anak",
      "ayunan",
      "perosotan",
      "tempat sampah",
      "patung"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "pasir",
      "ombak",
      "matahari",
      "payung",
      "handuk",
      "pakaian renang",
      "tabir surya",
      "kacamata hitam",
      "topi",
      "cangkang",
      "burung camar",
      "laut",
      "pasang surut",
      "selancar",
      "papan",
      "snorkeling",
      "masker",
      "sirip",
      "bola pantai",
      "es krim"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "buku",
      "rak",
      "katalog",
      "meminjam",
      "mengembalikan",
      "tanggal jatuh tempo",
      "pustakawan",
      "belajar",
      "tenang",
      "meja",
      "kursi",
      "komputer",
      "internet",
      "majalah",
      "koran",
      "fiksi",
      "non-fiksi",
      "referensi",
      "pinjaman",
      "kartu"
    ]
  },
  {
    "name": "At the Cinema",
    "words": ["tiket", "film", "popcorn", "minuman", "kursi", "layar", "trailer", "genre", "horor", "komedi", "aksi", "drama", "romantis", "sutradara", "aktor", "aktris", "subtitel", "3d", "waktu tayang", "konsesi"]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "potong rambut",
      "shampo",
      "kondisioner",
      "penata rambut",
      "gunting",
      "sisir",
      "blow-dry",
      "warna",
      "highlight",
      "trim",
      "poni",
      "keriting",
      "meluruskan",
      "janji temu",
      "cermin",
      "kursi",
      "jubah",
      "pisau cukur",
      "gel",
      "semprotan"
    ]
  }
];
