const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["kopi", "teh", "susu", "gula", "cawan", "pesanan", "menu", "meja", "barista", "resit", "wang baki", "bungkus", "ais", "panas", "sudu", "napkin", "krim", "espresso", "latte", "tip"]
  },
  {
    "name": "Weather Talk",
    "words": ["cerah", "hujan", "berawan", "berangin", "ribut", "salji", "panas", "sejuk", "suam", "nyaman", "ramalan", "payung", "kot", "suhu", "darjah", "musim", "lembap", "kering"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "troli",
      "bakul",
      "lorong",
      "kaunter bayaran",
      "juruwang",
      "resit",
      "beg",
      "buah-buahan",
      "sayur-sayuran",
      "roti",
      "produk tenusu",
      "daging",
      "beku",
      "tin",
      "rak",
      "harga",
      "jualan",
      "kod bar",
      "tunai",
      "kad"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": [
      "peta",
      "jalan",
      "lorong",
      "jalan besar",
      "kiri",
      "kanan",
      "terus",
      "sudut",
      "blok",
      "lampu isyarat",
      "persimpangan",
      "belok",
      "dekat",
      "jauh",
      "belakang",
      "depan",
      "sebelah",
      "antara",
      "bertentangan",
      "tanda"
    ]
  },
  {
    "name": "Making Small Talk",
    "words": [
      "hai",
      "hello",
      "apa khabar",
      "baik",
      "terima kasih",
      "anda",
      "cuaca",
      "baik",
      "buruk",
      "sibuk",
      "penat",
      "hujung minggu",
      "rancangan",
      "nikmati",
      "hari ini",
      "esok",
      "semalam",
      "seronok",
      "berjumpa",
      "lagi"
    ]
  },
  {
    "name": "At the Airport",
    "words": [
      "pas masuk",
      "pasport",
      "bagasi",
      "daftar masuk",
      "keselamatan",
      "pintu masuk",
      "penerbangan",
      "kelewatan",
      "berlepas",
      "tiba",
      "terminal",
      "tuntutan bagasi",
      "kastam",
      "tiket",
      "tempat duduk",
      "menaiki",
      "bawaan tangan",
      "kereta sorong",
      "visa",
      "bebas cukai"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menu",
      "pelayan",
      "tempahan",
      "pesanan",
      "pembuka selera",
      "hidangan utama",
      "pencuci mulut",
      "bil",
      "tip",
      "minuman",
      "air",
      "wain",
      "bir",
      "garpu",
      "pisau",
      "sudu",
      "pinggan",
      "gelas",
      "napkin",
      "istimewa"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "kaunter penerimaan",
      "daftar masuk",
      "daftar keluar",
      "bilik",
      "kunci",
      "tempahan",
      "bagasi",
      "lif",
      "sarapan",
      "wi-fi",
      "mandi",
      "tuala",
      "katil",
      "bantal",
      "selimut",
      "penghawa dingin",
      "dobi",
      "perkhidmatan",
      "peti keselamatan",
      "pemandangan"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "janji temu",
      "doktor",
      "jururawat",
      "gejala",
      "sakit",
      "demam",
      "batuk",
      "sakit kepala",
      "resipi",
      "ubat",
      "farmasi",
      "alergi",
      "tekanan darah",
      "suhu",
      "stetoskop",
      "pembalut",
      "suntikan",
      "x-ray",
      "diagnosis",
      "rawatan"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "bas",
      "kereta api",
      "metro",
      "tiket",
      "stesen",
      "perhentian",
      "jadual",
      "peta",
      "laluan",
      "platform",
      "tambang",
      "pertukaran",
      "penumpang",
      "pemandu",
      "konduktor",
      "kelewatan",
      "keluar",
      "masuk",
      "tempat duduk",
      "berdiri"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": ["baju", "seluar", "gaun", "kasut", "saiz", "warna", "harga", "jualan", "bilik persalinan", "juruwang", "resit", "beg", "jaket", "sweater", "skirt", "topi", "stokin", "jeans", "tali pinggang", "diskaun"]
  },
  {
    "name": "At the Gym",
    "words": [
      "treadmill",
      "pemberat",
      "yoga",
      "regangan",
      "jurulatih",
      "keahlian",
      "loker",
      "mandi",
      "tuala",
      "botol air",
      "senaman",
      "kardio",
      "kekuatan",
      "ulangan",
      "set",
      "pemanasan",
      "penyejukan",
      "dumbel",
      "barbel",
      "mesin"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "akaun",
      "pengeluaran",
      "deposit",
      "pinjaman",
      "faedah",
      "kad kredit",
      "kad debit",
      "ATM",
      "juruwang bank",
      "baki",
      "mata wang",
      "pertukaran",
      "cek",
      "simpanan",
      "pelaburan",
      "kata laluan",
      "pin",
      "penyata",
      "yuran",
      "pemindahan"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "pakej",
      "surat",
      "setem",
      "sampul surat",
      "alamat",
      "poskad",
      "parcel",
      "penghantaran",
      "penjejakan",
      "peti surat",
      "pengirim",
      "penerima",
      "berat",
      "saiz",
      "keutamaan",
      "ekspres",
      "mel udara",
      "kastam",
      "yuran",
      "resit"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "ubat",
      "resipi",
      "penahan sakit",
      "pembalut",
      "vitamin",
      "sirap ubat batuk",
      "alergi",
      "krim",
      "salap",
      "pil",
      "tablet",
      "kapsul",
      "ahli farmasi",
      "dos",
      "kesan sampingan",
      "isi semula",
      "antibiotik",
      "termometer",
      "topeng",
      "pencuci tangan"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "bangku",
      "pokok",
      "rumput",
      "laluan",
      "taman permainan",
      "air pancut",
      "anjing",
      "berkelah",
      "basikal",
      "joging",
      "bunga",
      "kolam",
      "itik",
      "teduh",
      "matahari",
      "kanak-kanak",
      "buaian",
      "gelongsor",
      "tong sampah",
      "patung"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "pasir",
      "ombak",
      "matahari",
      "payung",
      "tuala",
      "pakaian renang",
      "krim pelindung matahari",
      "cermin mata hitam",
      "topi",
      "kulit kerang",
      "burung camar",
      "lautan",
      "air pasang",
      "meluncur",
      "papan",
      "snorkeling",
      "topeng",
      "sirip",
      "bola pantai",
      "ais krim"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "buku",
      "rak buku",
      "katalog",
      "meminjam",
      "memulangkan",
      "tarikh akhir",
      "pustakawan",
      "belajar",
      "senyap",
      "meja",
      "kerusi",
      "komputer",
      "internet",
      "majalah",
      "akhbar",
      "fiksyen",
      "bukan fiksyen",
      "rujukan",
      "pinjaman",
      "kad"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "tiket",
      "filem",
      "bertih jagung",
      "minuman",
      "tempat duduk",
      "skrin",
      "treler",
      "genre",
      "seram",
      "komedi",
      "aksi",
      "drama",
      "romantik",
      "pengarah",
      "pelakon",
      "pelakon wanita",
      "sari kata",
      "3d",
      "waktu tayangan",
      "konsesi"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "potongan rambut",
      "syampu",
      "perapi",
      "pendandan rambut",
      "gunting",
      "sikat",
      "pengering rambut",
      "warna",
      "serlahan",
      "trim",
      "poni",
      "keriting",
      "meluruskan",
      "janji temu",
      "cermin",
      "kerusi",
      "jubah",
      "pisau cukur",
      "gel",
      "semburan"
    ]
  }
];
