const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["café", "chá", "leite", "açúcar", "xícara", "pedido", "cardápio", "mesa", "barista", "recibo", "troco", "para viagem", "gelado", "quente", "colher", "guardanapo", "creme", "espresso", "latte", "gorjeta"]
  },
  {
    "name": "Weather Talk",
    "words": ["ensolarado", "chuvoso", "nublado", "ventoso", "tempestuoso", "neve", "quente", "frio", "morno", "fresco", "previsão", "guarda-chuva", "casaco", "temperatura", "graus", "estação", "úmido", "seco"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "carrinho",
      "cesta",
      "corredor",
      "caixa",
      "caixa",
      "recibo",
      "sacola",
      "frutas",
      "legumes",
      "pão",
      "laticínios",
      "carne",
      "congelado",
      "enlatado",
      "prateleira",
      "preço",
      "promoção",
      "código de barras",
      "dinheiro",
      "cartão"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["mapa", "rua", "caminho", "avenida", "esquerda", "direita", "reto", "esquina", "quarteirão", "semáforo", "cruzamento", "virar", "perto", "longe", "atrás", "frente", "ao lado", "entre", "em frente", "placa"]
  },
  {
    "name": "Essential Conversations",
    "words": ["oi", "olá", "tudo bem", "bem", "obrigado", "você", "tempo", "bom", "ruim", "ocupado", "cansado", "fim de semana", "planos", "aproveitar", "hoje", "amanhã", "ontem", "legal", "encontrar", "de novo"]
  },
  {
    "name": "At the Airport",
    "words": [
      "cartão de embarque",
      "passaporte",
      "bagagem",
      "check-in",
      "segurança",
      "portão",
      "voo",
      "atraso",
      "partida",
      "chegada",
      "terminal",
      "reclamação de bagagem",
      "alfândega",
      "passagem",
      "assento",
      "embarque",
      "bagagem de mão",
      "carrinho de bebê",
      "visto",
      "duty-free"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "cardápio",
      "garçom",
      "reserva",
      "pedido",
      "aperitivo",
      "prato principal",
      "sobremesa",
      "conta",
      "gorjeta",
      "bebida",
      "água",
      "vinho",
      "cerveja",
      "garfo",
      "faca",
      "colher",
      "prato",
      "copo",
      "guardanapo",
      "especial"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "recepção",
      "check-in",
      "check-out",
      "quarto",
      "chave",
      "reserva",
      "bagagem",
      "elevador",
      "café da manhã",
      "wi-fi",
      "chuveiro",
      "toalha",
      "cama",
      "travesseiro",
      "cobertor",
      "ar condicionado",
      "lavanderia",
      "serviço",
      "cofre",
      "vista"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "consulta",
      "médico",
      "enfermeira",
      "sintomas",
      "dor",
      "febre",
      "tosse",
      "dor de cabeça",
      "receita",
      "remédio",
      "farmácia",
      "alergia",
      "pressão arterial",
      "temperatura",
      "estetoscópio",
      "curativo",
      "injeção",
      "raio-x",
      "diagnóstico",
      "tratamento"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "ônibus",
      "trem",
      "metrô",
      "bilhete",
      "estação",
      "ponto",
      "horário",
      "mapa",
      "rota",
      "plataforma",
      "tarifa",
      "baldeação",
      "passageiro",
      "motorista",
      "cobrador",
      "atraso",
      "saída",
      "entrada",
      "assento",
      "em pé"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": ["camisa", "calça", "vestido", "sapatos", "tamanho", "cor", "preço", "promoção", "provador", "caixa", "recibo", "sacola", "jaqueta", "blusa", "saia", "chapéu", "meias", "jeans", "cinto", "desconto"]
  },
  {
    "name": "At the Gym",
    "words": [
      "esteira",
      "pesos",
      "yoga",
      "alongamento",
      "personal trainer",
      "mensalidade",
      "armário",
      "chuveiro",
      "toalha",
      "garrafa de água",
      "exercício",
      "cardio",
      "força",
      "repetições",
      "séries",
      "aquecimento",
      "resfriamento",
      "halteres",
      "barra",
      "aparelho"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "conta",
      "saque",
      "depósito",
      "empréstimo",
      "juros",
      "cartão de crédito",
      "cartão de débito",
      "caixa eletrônico",
      "caixa",
      "saldo",
      "moeda",
      "câmbio",
      "cheque",
      "poupança",
      "investimento",
      "senha",
      "pin",
      "extrato",
      "tarifa",
      "transferência"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "pacote",
      "carta",
      "selo",
      "envelope",
      "endereço",
      "cartão postal",
      "pacote",
      "entrega",
      "rastreamento",
      "caixa de correio",
      "remetente",
      "destinatário",
      "peso",
      "tamanho",
      "prioridade",
      "expresso",
      "correio aéreo",
      "alfândega",
      "taxa",
      "recibo"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "remédio",
      "receita",
      "analgésico",
      "curativo",
      "vitaminas",
      "xarope para tosse",
      "alergia",
      "creme",
      "pomada",
      "pílula",
      "comprimido",
      "cápsula",
      "farmacêutico",
      "dosagem",
      "efeitos colaterais",
      "reposição",
      "antibiótico",
      "termômetro",
      "máscara",
      "desinfetante"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "banco",
      "árvore",
      "grama",
      "caminho",
      "playground",
      "chafariz",
      "cachorro",
      "piquenique",
      "bicicleta",
      "corrida",
      "flores",
      "lago",
      "pato",
      "sombra",
      "sol",
      "crianças",
      "balanço",
      "escorregador",
      "lixeira",
      "estátua"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "areia",
      "ondas",
      "sol",
      "guarda-sol",
      "toalha",
      "roupa de banho",
      "protetor solar",
      "óculos de sol",
      "chapéu",
      "conchas",
      "gaivota",
      "mar",
      "maré",
      "surfe",
      "prancha",
      "snorkel",
      "máscara",
      "nadadeiras",
      "bola de praia",
      "sorvete"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "livro",
      "prateleira",
      "catálogo",
      "emprestar",
      "devolver",
      "data de devolução",
      "bibliotecário",
      "estudar",
      "silêncio",
      "mesa",
      "cadeira",
      "computador",
      "internet",
      "revista",
      "jornal",
      "ficção",
      "não-ficção",
      "referência",
      "empréstimo",
      "carteirinha"
    ]
  },
  {
    "name": "At the Cinema",
    "words": ["ingresso", "filme", "pipoca", "bebida", "poltrona", "tela", "trailer", "gênero", "terror", "comédia", "ação", "drama", "romance", "diretor", "ator", "atriz", "legenda", "3d", "horário", "concessão"]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "corte de cabelo",
      "xampu",
      "condicionador",
      "cabeleireiro",
      "tesoura",
      "pente",
      "secador",
      "tinta",
      "mechas",
      "aparar",
      "franja",
      "cachos",
      "alisamento",
      "hora marcada",
      "espelho",
      "cadeira",
      "capa",
      "navalha",
      "gel",
      "spray"
    ]
  }
];
