const categories = [
  {
    "name": "At the Coffee Shop",
    "words": [
      "Kaffee",
      "Tee",
      "Milch",
      "Zucker",
      "Tasse",
      "Bestellung",
      "Speisekarte",
      "Tisch",
      "Barista",
      "Quittung",
      "Wechselgeld",
      "zum Mitnehmen",
      "Eis",
      "heiß",
      "Löffel",
      "Serviette",
      "Sahne",
      "Espresso",
      "Latte",
      "Trinkgeld"
    ]
  },
  {
    "name": "Weather Talk",
    "words": ["sonnig", "regnerisch", "bewölkt", "windig", "stürmisch", "Schnee", "heiß", "kalt", "warm", "kühl", "Vorhersage", "Regenschirm", "Mantel", "Temperatur", "Grad", "Jahreszeit", "feucht", "trocken"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "Wagen",
      "Korb",
      "Gang",
      "Kasse",
      "Kassierer",
      "Quittung",
      "Tüte",
      "Obst",
      "Gemüse",
      "Brot",
      "Milchprodukte",
      "Fleisch",
      "gefroren",
      "konserviert",
      "Regal",
      "Preis",
      "Angebot",
      "Barcode",
      "Bargeld",
      "Karte"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["Karte", "Straße", "Weg", "Allee", "links", "rechts", "geradeaus", "Ecke", "Block", "Ampel", "Kreuzung", "abbiegen", "nah", "fern", "hinter", "vor", "neben", "zwischen", "gegenüber", "Schild"]
  },
  {
    "name": "Making Small Talk",
    "words": ["hallo", "hi", "wie", "gut", "danke", "du", "Wetter", "gut", "schlecht", "beschäftigt", "müde", "Wochenende", "Pläne", "genießen", "heute", "morgen", "gestern", "schön", "treffen", "wieder"]
  },
  {
    "name": "At the Airport",
    "words": [
      "Bordkarte",
      "Reisepass",
      "Gepäck",
      "Check-in",
      "Sicherheit",
      "Gate",
      "Flug",
      "Verspätung",
      "Abflug",
      "Ankunft",
      "Terminal",
      "Gepäckausgabe",
      "Zoll",
      "Ticket",
      "Sitzplatz",
      "Boarding",
      "Handgepäck",
      "Kinderwagen",
      "Visum",
      "zollfrei"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "Speisekarte",
      "Kellner",
      "Reservierung",
      "Bestellung",
      "Vorspeise",
      "Hauptgericht",
      "Dessert",
      "Rechnung",
      "Trinkgeld",
      "Getränk",
      "Wasser",
      "Wein",
      "Bier",
      "Gabel",
      "Messer",
      "Löffel",
      "Teller",
      "Glas",
      "Serviette",
      "Spezial"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "Rezeption",
      "Check-in",
      "Check-out",
      "Zimmer",
      "Schlüssel",
      "Reservierung",
      "Gepäck",
      "Aufzug",
      "Frühstück",
      "WLAN",
      "Dusche",
      "Handtuch",
      "Bett",
      "Kissen",
      "Decke",
      "Klimaanlage",
      "Wäscherei",
      "Service",
      "Safe",
      "Aussicht"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "Termin",
      "Arzt",
      "Krankenschwester",
      "Symptome",
      "Schmerzen",
      "Fieber",
      "Husten",
      "Kopfschmerzen",
      "Rezept",
      "Medizin",
      "Apotheke",
      "Allergie",
      "Blutdruck",
      "Temperatur",
      "Stethoskop",
      "Verband",
      "Injektion",
      "Röntgen",
      "Diagnose",
      "Behandlung"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "Bus",
      "Zug",
      "U-Bahn",
      "Ticket",
      "Bahnhof",
      "Haltestelle",
      "Fahrplan",
      "Karte",
      "Route",
      "Bahnsteig",
      "Fahrpreis",
      "Umsteigen",
      "Fahrgast",
      "Fahrer",
      "Schaffner",
      "Verspätung",
      "Ausgang",
      "Eingang",
      "Sitzplatz",
      "Stehen"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": ["Hemd", "Hose", "Kleid", "Schuhe", "Größe", "Farbe", "Preis", "Angebot", "Umkleidekabine", "Kassierer", "Quittung", "Tüte", "Jacke", "Pullover", "Rock", "Hut", "Socken", "Jeans", "Gürtel", "Rabatt"]
  },
  {
    "name": "At the Gym",
    "words": [
      "Laufband",
      "Gewichte",
      "Yoga",
      "Dehnen",
      "Trainer",
      "Mitgliedschaft",
      "Schließfach",
      "Dusche",
      "Handtuch",
      "Wasserflasche",
      "Übung",
      "Cardio",
      "Kraft",
      "Wiederholungen",
      "Sätze",
      "Aufwärmen",
      "Abkühlen",
      "Hantel",
      "Langhantel",
      "Maschine"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "Konto",
      "Abhebung",
      "Einzahlung",
      "Darlehen",
      "Zinsen",
      "Kreditkarte",
      "Debitkarte",
      "Geldautomat",
      "Schalterbeamter",
      "Saldo",
      "Währung",
      "Wechsel",
      "Scheck",
      "Sparen",
      "Investition",
      "Passwort",
      "PIN",
      "Kontoauszug",
      "Gebühr",
      "Überweisung"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "Paket",
      "Brief",
      "Briefmarke",
      "Umschlag",
      "Adresse",
      "Postkarte",
      "Päckchen",
      "Lieferung",
      "Sendungsverfolgung",
      "Briefkasten",
      "Absender",
      "Empfänger",
      "Gewicht",
      "Größe",
      "Priorität",
      "Express",
      "Luftpost",
      "Zoll",
      "Gebühr",
      "Quittung"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "Medizin",
      "Rezept",
      "Schmerzmittel",
      "Verband",
      "Vitamine",
      "Hustensaft",
      "Allergie",
      "Creme",
      "Salbe",
      "Pille",
      "Tablette",
      "Kapsel",
      "Apotheker",
      "Dosierung",
      "Nebenwirkungen",
      "Nachfüllung",
      "Antibiotikum",
      "Thermometer",
      "Maske",
      "Desinfektionsmittel"
    ]
  },
  {
    "name": "At the Park",
    "words": ["Bank", "Baum", "Gras", "Pfad", "Spielplatz", "Brunnen", "Hund", "Picknick", "Fahrrad", "Joggen", "Blumen", "Teich", "Ente", "Schatten", "Sonne", "Kinder", "Schaukel", "Rutsche", "Mülleimer", "Statue"]
  },
  {
    "name": "At the Beach",
    "words": [
      "Sand",
      "Wellen",
      "Sonne",
      "Sonnenschirm",
      "Handtuch",
      "Badeanzug",
      "Sonnencreme",
      "Sonnenbrille",
      "Hut",
      "Muscheln",
      "Möwe",
      "Ozean",
      "Gezeiten",
      "Surfen",
      "Brett",
      "Schnorchel",
      "Maske",
      "Flossen",
      "Strandball",
      "Eis"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "Buch",
      "Regal",
      "Katalog",
      "ausleihen",
      "zurückgeben",
      "Fälligkeitsdatum",
      "Bibliothekar",
      "studieren",
      "ruhig",
      "Schreibtisch",
      "Stuhl",
      "Computer",
      "Internet",
      "Magazin",
      "Zeitung",
      "Fiktion",
      "Sachbuch",
      "Referenz",
      "Ausleihe",
      "Karte"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "Ticket",
      "Film",
      "Popcorn",
      "Getränk",
      "Sitzplatz",
      "Leinwand",
      "Trailer",
      "Genre",
      "Horror",
      "Komödie",
      "Action",
      "Drama",
      "Romantik",
      "Regisseur",
      "Schauspieler",
      "Schauspielerin",
      "Untertitel",
      "3D",
      "Vorstellungszeit",
      "Imbiss"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": ["Haarschnitt", "Shampoo", "Spülung", "Stylist", "Schere", "Kamm", "Föhnen", "Farbe", "Strähnchen", "Trimmen", "Pony", "Locken", "Glätten", "Termin", "Spiegel", "Stuhl", "Umhang", "Rasierer", "Gel", "Spray"]
  }
];
