const categories = [
  {
    "name": "At the Coffee Shop",
    "words": ["café", "thé", "lait", "sucre", "tasse", "commande", "menu", "table", "barista", "ticket", "monnaie", "à emporter", "glacé", "chaud", "cuillère", "serviette", "crème", "espresso", "latte", "pourboire"]
  },
  {
    "name": "Weather Talk",
    "words": ["ensoleillé", "pluvieux", "nuageux", "venteux", "orageux", "neige", "chaud", "froid", "tiède", "frais", "prévisions", "parapluie", "manteau", "température", "degrés", "saison", "humide", "sec"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "caddie",
      "panier",
      "rayon",
      "caisse",
      "caissier",
      "ticket de caisse",
      "sac",
      "fruits",
      "légumes",
      "pain",
      "produits laitiers",
      "viande",
      "surgelé",
      "en conserve",
      "étagère",
      "prix",
      "promotion",
      "code-barres",
      "espèces",
      "carte"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": [
      "plan",
      "rue",
      "route",
      "avenue",
      "gauche",
      "droite",
      "tout droit",
      "coin",
      "pâté de maisons",
      "feu rouge",
      "intersection",
      "tourner",
      "près",
      "loin",
      "derrière",
      "devant",
      "à côté",
      "entre",
      "en face",
      "panneau"
    ]
  },
  {
    "name": "Making Small Talk",
    "words": [
      "bonjour",
      "salut",
      "comment ça va",
      "bien",
      "merci",
      "vous",
      "temps",
      "bien",
      "mal",
      "occupé",
      "fatigué",
      "week-end",
      "projets",
      "profiter",
      "aujourd'hui",
      "demain",
      "hier",
      "agréable",
      "rencontrer",
      "à nouveau"
    ]
  },
  {
    "name": "At the Airport",
    "words": [
      "carte d'embarquement",
      "passeport",
      "bagages",
      "enregistrement",
      "sécurité",
      "porte d'embarquement",
      "vol",
      "retard",
      "départ",
      "arrivée",
      "terminal",
      "récupération des bagages",
      "douane",
      "billet",
      "siège",
      "embarquement",
      "bagage à main",
      "poussette",
      "visa",
      "hors taxes"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "carte",
      "serveur",
      "réservation",
      "commande",
      "entrée",
      "plat principal",
      "dessert",
      "addition",
      "pourboire",
      "boisson",
      "eau",
      "vin",
      "bière",
      "fourchette",
      "couteau",
      "cuillère",
      "assiette",
      "verre",
      "serviette",
      "spécialité"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "réception",
      "enregistrement",
      "départ",
      "chambre",
      "clé",
      "réservation",
      "bagages",
      "ascenseur",
      "petit déjeuner",
      "wi-fi",
      "douche",
      "serviette",
      "lit",
      "oreiller",
      "couverture",
      "climatisation",
      "blanchisserie",
      "service",
      "coffre-fort",
      "vue"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "rendez-vous",
      "médecin",
      "infirmière",
      "symptômes",
      "douleur",
      "fièvre",
      "toux",
      "mal de tête",
      "ordonnance",
      "médicament",
      "pharmacie",
      "allergie",
      "tension artérielle",
      "température",
      "stéthoscope",
      "pansement",
      "injection",
      "radiographie",
      "diagnostic",
      "traitement"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "bus",
      "train",
      "métro",
      "ticket",
      "gare",
      "arrêt",
      "horaires",
      "plan",
      "itinéraire",
      "quai",
      "tarif",
      "correspondance",
      "passager",
      "chauffeur",
      "contrôleur",
      "retard",
      "sortie",
      "entrée",
      "siège",
      "debout"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "chemise",
      "pantalon",
      "robe",
      "chaussures",
      "taille",
      "couleur",
      "prix",
      "promotion",
      "cabine d'essayage",
      "caissier",
      "ticket de caisse",
      "sac",
      "veste",
      "pull",
      "jupe",
      "chapeau",
      "chaussettes",
      "jean",
      "ceinture",
      "réduction"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "tapis de course",
      "poids",
      "yoga",
      "étirements",
      "entraîneur",
      "abonnement",
      "casier",
      "douche",
      "serviette",
      "bouteille d'eau",
      "exercice",
      "cardio",
      "force",
      "répétitions",
      "séries",
      "échauffement",
      "retour au calme",
      "haltère",
      "barre",
      "machine"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "compte",
      "retrait",
      "dépôt",
      "prêt",
      "intérêts",
      "carte de crédit",
      "carte de débit",
      "distributeur automatique",
      "guichetier",
      "solde",
      "devise",
      "change",
      "chèque",
      "épargne",
      "investissement",
      "mot de passe",
      "code pin",
      "relevé de compte",
      "frais",
      "virement"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "paquet",
      "lettre",
      "timbre",
      "enveloppe",
      "adresse",
      "carte postale",
      "colis",
      "livraison",
      "suivi",
      "boîte aux lettres",
      "expéditeur",
      "destinataire",
      "poids",
      "taille",
      "prioritaire",
      "express",
      "par avion",
      "douane",
      "frais",
      "reçu"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "médicament",
      "ordonnance",
      "antalgique",
      "pansement",
      "vitamines",
      "sirop contre la toux",
      "allergie",
      "crème",
      "pommade",
      "pilule",
      "comprimé",
      "capsule",
      "pharmacien",
      "dosage",
      "effets secondaires",
      "renouvellement",
      "antibiotique",
      "thermomètre",
      "masque",
      "gel hydroalcoolique"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "banc",
      "arbre",
      "pelouse",
      "chemin",
      "aire de jeux",
      "fontaine",
      "chien",
      "pique-nique",
      "vélo",
      "jogging",
      "fleurs",
      "étang",
      "canard",
      "ombre",
      "soleil",
      "enfants",
      "balançoire",
      "toboggan",
      "poubelle",
      "statue"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "sable",
      "vagues",
      "soleil",
      "parasol",
      "serviette",
      "maillot de bain",
      "crème solaire",
      "lunettes de soleil",
      "chapeau",
      "coquillages",
      "goéland",
      "océan",
      "marée",
      "surf",
      "planche",
      "plongée avec tuba",
      "masque",
      "palmes",
      "ballon de plage",
      "glace"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "livre",
      "étagère",
      "catalogue",
      "emprunter",
      "rendre",
      "date limite",
      "bibliothécaire",
      "étudier",
      "silence",
      "bureau",
      "chaise",
      "ordinateur",
      "internet",
      "magazine",
      "journal",
      "fiction",
      "non-fiction",
      "référence",
      "emprunt",
      "carte"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "billet",
      "film",
      "pop-corn",
      "boisson",
      "siège",
      "écran",
      "bande-annonce",
      "genre",
      "horreur",
      "comédie",
      "action",
      "drame",
      "romance",
      "réalisateur",
      "acteur",
      "actrice",
      "sous-titres",
      "3d",
      "séance",
      "confiserie"
    ]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "coupe de cheveux",
      "shampoing",
      "après-shampoing",
      "coiffeur",
      "ciseaux",
      "peigne",
      "brushing",
      "couleur",
      "mèches",
      "taille",
      "frange",
      "boucles",
      "lissage",
      "rendez-vous",
      "miroir",
      "fauteuil",
      "cape",
      "rasoir",
      "gel",
      "laque"
    ]
  }
];
