const categories = [
  {
    "name": "At the Coffee Shop",
    "words": [
      "kawa",
      "herbata",
      "mleko",
      "cukier",
      "filiżanka",
      "zamówienie",
      "menu",
      "stolik",
      "barista",
      "paragon",
      "reszta",
      "na wynos",
      "mrożona",
      "gorąca",
      "łyżeczka",
      "serwetka",
      "śmietanka",
      "espresso",
      "latte",
      "napiwek"
    ]
  },
  {
    "name": "Weather Talk",
    "words": [
      "słonecznie",
      "deszczowo",
      "pochmurno",
      "wietrznie",
      "burzowo",
      "śnieg",
      "gorąco",
      "zimno",
      "ciepło",
      "chłodno",
      "prognoza pogody",
      "parasol",
      "płaszcz",
      "temperatura",
      "stopnie",
      "pora roku",
      "wilgotno",
      "sucho"
    ]
  },
  {
    "name": "In the Supermarket",
    "words": ["wózek", "koszyk", "alejka", "kasa", "kasjer", "paragon", "torba", "owoce", "warzywa", "chleb", "nabiał", "mięso", "mrożone", "konserwy", "półka", "cena", "wyprzedaż", "kod kreskowy", "gotówka", "karta"]
  },
  {
    "name": "Asking for Directions",
    "words": ["mapa", "ulica", "droga", "aleja", "lewo", "prawo", "prosto", "róg", "blok", "światła", "skrzyżowanie", "skręcić", "blisko", "daleko", "za", "przed", "obok", "między", "naprzeciwko", "znak"]
  },
  {
    "name": "Essential Conversations",
    "words": ["cześć", "siema", "jak się masz", "dobrze", "dziękuję", "ty", "pogoda", "dobrze", "źle", "zajęty", "zmęczony", "weekend", "plany", "cieszyć się", "dzisiaj", "jutro", "wczoraj", "miło", "spotkać", "znowu"]
  },
  {
    "name": "At the Airport",
    "words": [
      "karta pokładowa",
      "paszport",
      "bagaż",
      "odprawa",
      "kontrola bezpieczeństwa",
      "bramka",
      "lot",
      "opóźnienie",
      "odlot",
      "przylot",
      "terminal",
      "odbiór bagażu",
      "cło",
      "bilet",
      "miejsce",
      "wejście na pokład",
      "bagaż podręczny",
      "wózek dziecięcy",
      "wiza",
      "bezcłowy"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menu",
      "kelner",
      "rezerwacja",
      "zamówienie",
      "przystawka",
      "danie główne",
      "deser",
      "rachunek",
      "napiwek",
      "napój",
      "woda",
      "wino",
      "piwo",
      "widelec",
      "nóż",
      "łyżka",
      "talerz",
      "szklanka",
      "serwetka",
      "specjalność"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "recepcja",
      "zameldowanie",
      "wymeldowanie",
      "pokój",
      "klucz",
      "rezerwacja",
      "bagaż",
      "winda",
      "śniadanie",
      "wi-fi",
      "prysznic",
      "ręcznik",
      "łóżko",
      "poduszka",
      "koc",
      "klimatyzacja",
      "pralnia",
      "serwis",
      "sejf",
      "widok"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "wizyta",
      "lekarz",
      "pielęgniarka",
      "objawy",
      "ból",
      "gorączka",
      "kaszel",
      "ból głowy",
      "recepta",
      "lek",
      "apteka",
      "alergia",
      "ciśnienie krwi",
      "temperatura",
      "stetoskop",
      "bandaż",
      "zastrzyk",
      "rentgen",
      "diagnoza",
      "leczenie"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "autobus",
      "pociąg",
      "metro",
      "bilet",
      "stacja",
      "przystanek",
      "rozkład jazdy",
      "mapa",
      "trasa",
      "peron",
      "opłata",
      "przesiadka",
      "pasażer",
      "kierowca",
      "konduktor",
      "opóźnienie",
      "wyjście",
      "wejście",
      "miejsce siedzące",
      "stojący"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "koszula",
      "spodnie",
      "sukienka",
      "buty",
      "rozmiar",
      "kolor",
      "cena",
      "wyprzedaż",
      "przymierzalnia",
      "kasjer",
      "paragon",
      "torba",
      "kurtka",
      "sweter",
      "spódnica",
      "czapka",
      "skarpetki",
      "dżinsy",
      "pasek",
      "zniżka"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "bieżnia",
      "ciężary",
      "joga",
      "rozciąganie",
      "trener",
      "karnet",
      "szafka",
      "prysznic",
      "ręcznik",
      "butelka wody",
      "ćwiczenie",
      "cardio",
      "siła",
      "powtórzenia",
      "serie",
      "rozgrzewka",
      "schłodzenie",
      "hantle",
      "sztanga",
      "maszyna"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "konto",
      "wypłata",
      "wpłata",
      "kredyt",
      "odsetki",
      "karta kredytowa",
      "karta debetowa",
      "bankomat",
      "kasjer bankowy",
      "saldo",
      "waluta",
      "wymiana",
      "czek",
      "oszczędności",
      "inwestycja",
      "hasło",
      "pin",
      "wyciąg z konta",
      "opłata",
      "przelew"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "paczka",
      "list",
      "znaczek",
      "koperta",
      "adres",
      "pocztówka",
      "paczka",
      "dostawa",
      "śledzenie",
      "skrzynka pocztowa",
      "nadawca",
      "odbiorca",
      "waga",
      "rozmiar",
      "priorytet",
      "ekspres",
      "lotnicza",
      "cło",
      "opłata",
      "potwierdzenie"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "lek",
      "recepta",
      "środek przeciwbólowy",
      "bandaż",
      "witaminy",
      "syrop na kaszel",
      "alergia",
      "krem",
      "maść",
      "pigułka",
      "tabletka",
      "kapsułka",
      "farmaceuta",
      "dawkowanie",
      "skutki uboczne",
      "uzupełnienie",
      "antybiotyk",
      "termometr",
      "maska",
      "środek dezynfekujący"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "ławka",
      "drzewo",
      "trawa",
      "ścieżka",
      "plac zabaw",
      "fontanna",
      "pies",
      "piknik",
      "rower",
      "bieganie",
      "kwiaty",
      "staw",
      "kaczka",
      "cień",
      "słońce",
      "dzieci",
      "huśtawka",
      "zjeżdżalnia",
      "kosz na śmieci",
      "pomnik"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "piasek",
      "fale",
      "słońce",
      "parasol",
      "ręcznik",
      "strój kąpielowy",
      "krem do opalania",
      "okulary przeciwsłoneczne",
      "kapelusz",
      "muszle",
      "mewa",
      "ocean",
      "przypływ",
      "surfing",
      "deska",
      "snorkeling",
      "maska",
      "płetwy",
      "piłka plażowa",
      "lody"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "książka",
      "półka",
      "katalog",
      "wypożyczyć",
      "zwrócić",
      "termin zwrotu",
      "bibliotekarz",
      "uczyć się",
      "cisza",
      "biurko",
      "krzesło",
      "komputer",
      "internet",
      "czasopismo",
      "gazeta",
      "fikcja",
      "non-fiction",
      "referencja",
      "wypożyczenie",
      "karta"
    ]
  },
  {
    "name": "At the Cinema",
    "words": ["bilet", "film", "popcorn", "napój", "miejsce", "ekran", "zwiastun", "gatunek", "horror", "komedia", "akcja", "dramat", "romans", "reżyser", "aktor", "aktorka", "napisy", "3d", "godzina seansu", "koncesja"]
  },
  {
    "name": "At the Hair Salon",
    "words": [
      "strzyżenie",
      "szampon",
      "odżywka",
      "fryzjer",
      "nożyczki",
      "grzebień",
      "suszenie",
      "kolor",
      "pasemka",
      "podcięcie",
      "grzywka",
      "loki",
      "prostowanie",
      "wizyta",
      "lustro",
      "krzesło",
      "peleryna",
      "maszynka do golenia",
      "żel",
      "spray"
    ]
  }
];
