const categories = [
  {
    "name": "At the Coffee Shop",
    "words": [
      "caffè",
      "tè",
      "latte",
      "zucchero",
      "tazza",
      "ordine",
      "menù",
      "tavolo",
      "barista",
      "scontrino",
      "resto",
      "da asporto",
      "ghiacciato",
      "caldo",
      "cucchiaio",
      "tovagliolo",
      "panna",
      "espresso",
      "latte macchiato",
      "mancia"
    ]
  },
  {
    "name": "Weather Talk",
    "words": ["soleggiato", "piovoso", "nuvoloso", "ventoso", "tempestoso", "neve", "caldo", "freddo", "tiepido", "fresco", "previsioni", "ombrello", "cappotto", "temperatura", "gradi", "stagione", "umido", "secco"]
  },
  {
    "name": "In the Supermarket",
    "words": [
      "carrello",
      "cestino",
      "corsia",
      "cassa",
      "cassiere",
      "scontrino",
      "sacchetto",
      "frutta",
      "verdura",
      "pane",
      "latticini",
      "carne",
      "congelato",
      "inscatolato",
      "scaffale",
      "prezzo",
      "offerta",
      "codice a barre",
      "contanti",
      "carta"
    ]
  },
  {
    "name": "Asking for Directions",
    "words": ["mappa", "via", "strada", "viale", "sinistra", "destra", "dritto", "angolo", "isolato", "semaforo", "incrocio", "girare", "vicino", "lontano", "dietro", "davanti", "accanto", "tra", "di fronte", "cartello"]
  },
  {
    "name": "Making Small Talk",
    "words": ["ciao", "salve", "come va", "bene", "grazie", "tu", "tempo", "bene", "male", "occupato", "stanco", "fine settimana", "piani", "godere", "oggi", "domani", "ieri", "piacevole", "incontrare", "di nuovo"]
  },
  {
    "name": "At the Airport",
    "words": [
      "carta d'imbarco",
      "passaporto",
      "bagaglio",
      "check-in",
      "sicurezza",
      "gate",
      "volo",
      "ritardo",
      "partenza",
      "arrivo",
      "terminal",
      "ritiro bagagli",
      "dogana",
      "biglietto",
      "posto",
      "imbarco",
      "bagaglio a mano",
      "passeggino",
      "visto",
      "duty-free"
    ]
  },
  {
    "name": "At the Restaurant",
    "words": [
      "menù",
      "cameriere",
      "prenotazione",
      "ordine",
      "antipasto",
      "piatto principale",
      "dessert",
      "conto",
      "mancia",
      "bevanda",
      "acqua",
      "vino",
      "birra",
      "forchetta",
      "coltello",
      "cucchiaio",
      "piatto",
      "bicchiere",
      "tovagliolo",
      "speciale"
    ]
  },
  {
    "name": "At the Hotel",
    "words": [
      "reception",
      "check-in",
      "check-out",
      "camera",
      "chiave",
      "prenotazione",
      "bagaglio",
      "ascensore",
      "colazione",
      "wi-fi",
      "doccia",
      "asciugamano",
      "letto",
      "cuscino",
      "coperta",
      "aria condizionata",
      "lavanderia",
      "servizio",
      "cassaforte",
      "vista"
    ]
  },
  {
    "name": "At the Doctor's Office",
    "words": [
      "appuntamento",
      "medico",
      "infermiera",
      "sintomi",
      "dolore",
      "febbre",
      "tosse",
      "mal di testa",
      "ricetta",
      "medicina",
      "farmacia",
      "allergia",
      "pressione sanguigna",
      "temperatura",
      "stetoscopio",
      "bendaggio",
      "iniezione",
      "radiografia",
      "diagnosi",
      "trattamento"
    ]
  },
  {
    "name": "Public Transportation",
    "words": [
      "autobus",
      "treno",
      "metropolitana",
      "biglietto",
      "stazione",
      "fermata",
      "orario",
      "mappa",
      "percorso",
      "binario",
      "tariffa",
      "trasferimento",
      "passeggero",
      "autista",
      "controllore",
      "ritardo",
      "uscita",
      "entrata",
      "posto a sedere",
      "in piedi"
    ]
  },
  {
    "name": "Shopping for Clothes",
    "words": [
      "camicia",
      "pantaloni",
      "vestito",
      "scarpe",
      "taglia",
      "colore",
      "prezzo",
      "offerta",
      "camerino",
      "cassiere",
      "scontrino",
      "sacchetto",
      "giacca",
      "maglione",
      "gonna",
      "cappello",
      "calzini",
      "jeans",
      "cintura",
      "sconto"
    ]
  },
  {
    "name": "At the Gym",
    "words": [
      "tapis roulant",
      "pesi",
      "yoga",
      "stretching",
      "istruttore",
      "abbonamento",
      "armadietto",
      "doccia",
      "asciugamano",
      "bottiglia d'acqua",
      "esercizio",
      "cardio",
      "forza",
      "ripetizioni",
      "serie",
      "riscaldamento",
      "defaticamento",
      "manubrio",
      "bilanciere",
      "macchina"
    ]
  },
  {
    "name": "At the Bank",
    "words": [
      "conto",
      "prelievo",
      "deposito",
      "prestito",
      "interesse",
      "carta di credito",
      "carta di debito",
      "bancomat",
      "cassiere",
      "saldo",
      "valuta",
      "cambio",
      "assegno",
      "risparmio",
      "investimento",
      "password",
      "pin",
      "estratto conto",
      "commissione",
      "trasferimento"
    ]
  },
  {
    "name": "At the Post Office",
    "words": [
      "pacco",
      "lettera",
      "francobollo",
      "busta",
      "indirizzo",
      "cartolina",
      "pacchetto",
      "consegna",
      "tracciamento",
      "cassetta postale",
      "mittente",
      "destinatario",
      "peso",
      "dimensione",
      "priorità",
      "espresso",
      "posta aerea",
      "dogana",
      "commissione",
      "ricevuta"
    ]
  },
  {
    "name": "At the Pharmacy",
    "words": [
      "medicina",
      "ricetta",
      "antidolorifico",
      "bendaggio",
      "vitamine",
      "sciroppo per la tosse",
      "allergia",
      "crema",
      "unguento",
      "pillola",
      "compressa",
      "capsula",
      "farmacista",
      "dosaggio",
      "effetti collaterali",
      "ricarica",
      "antibiotico",
      "termometro",
      "mascherina",
      "disinfettante"
    ]
  },
  {
    "name": "At the Park",
    "words": [
      "panchina",
      "albero",
      "erba",
      "sentiero",
      "parco giochi",
      "fontana",
      "cane",
      "picnic",
      "bicicletta",
      "jogging",
      "fiori",
      "laghetto",
      "anatra",
      "ombra",
      "sole",
      "bambini",
      "altalena",
      "scivolo",
      "cestino dei rifiuti",
      "statua"
    ]
  },
  {
    "name": "At the Beach",
    "words": [
      "sabbia",
      "onde",
      "sole",
      "ombrellone",
      "asciugamano",
      "costume da bagno",
      "crema solare",
      "occhiali da sole",
      "cappello",
      "conchiglie",
      "gabbiano",
      "oceano",
      "marea",
      "surf",
      "tavola",
      "snorkeling",
      "maschera",
      "pinne",
      "palla da spiaggia",
      "gelato"
    ]
  },
  {
    "name": "At the Library",
    "words": [
      "libro",
      "scaffale",
      "catalogo",
      "prendere in prestito",
      "restituire",
      "data di scadenza",
      "bibliotecario",
      "studiare",
      "silenzio",
      "scrivania",
      "sedia",
      "computer",
      "internet",
      "rivista",
      "giornale",
      "fiction",
      "non-fiction",
      "riferimento",
      "prestito",
      "tessera"
    ]
  },
  {
    "name": "At the Cinema",
    "words": [
      "biglietto",
      "film",
      "popcorn",
      "bevanda",
      "posto",
      "schermo",
      "trailer",
      "genere",
      "horror",
      "commedia",
      "azione",
      "dramma",
      "romantico",
      "regista",
      "attore",
      "attrice",
      "sottotitoli",
      "3d",
      "orario dello spettacolo",
      "concessione"
    ]
  }
];
