// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACluIm0NV4m_R_3Ba146Ywf8OALzYzACs',
    appId: '1:104439269977:web:c4ad1b9f6d77a66e64bf48',
    messagingSenderId: '104439269977',
    projectId: 'noble-descent-420612',
    authDomain: 'noble-descent-420612.firebaseapp.com',
    storageBucket: 'noble-descent-420612.appspot.com',
    measurementId: 'G-VWV947PPFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWenp03TlyOyt_3N4L9AWRCw2XK3uV8FA',
    appId: '1:104439269977:android:a5e9c424cab1818964bf48',
    messagingSenderId: '104439269977',
    projectId: 'noble-descent-420612',
    storageBucket: 'noble-descent-420612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_oYpQrK_b2asbvJzVOtxf8S1fXEFEwk',
    appId: '1:104439269977:ios:3c0f1c2cb49afef064bf48',
    messagingSenderId: '104439269977',
    projectId: 'noble-descent-420612',
    storageBucket: 'noble-descent-420612.appspot.com',
    iosBundleId: 'com.example.auralearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_oYpQrK_b2asbvJzVOtxf8S1fXEFEwk',
    appId: '1:104439269977:ios:3c0f1c2cb49afef064bf48',
    messagingSenderId: '104439269977',
    projectId: 'noble-descent-420612',
    storageBucket: 'noble-descent-420612.appspot.com',
    iosBundleId: 'com.example.auralearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACluIm0NV4m_R_3Ba146Ywf8OALzYzACs',
    appId: '1:104439269977:web:d38ab3f9ce2073b464bf48',
    messagingSenderId: '104439269977',
    projectId: 'noble-descent-420612',
    authDomain: 'noble-descent-420612.firebaseapp.com',
    storageBucket: 'noble-descent-420612.appspot.com',
    measurementId: 'G-EVJ3WSXG3D',
  );
}
