final Map<String, List<String>> scenarioKeywords = {
  "Einstein has a philosophical conversation about life with a duckling.": ["einstein", "philosophical", "conversation", "about", "life"],
  "Ordering a coffee": ["coffee", "order", "barista", "menu", "café"],
  "A conversation between 2 product managers about compliance and GDPR": ["conversation", "between", "product", "managers", "about"],
  "Two software engineers discuss the latest advancements in AI": ["technology", "code", "debug", "software", "update"],
  "A conversation between a product manager and a software engineer": ["technology", "code", "debug", "software", "update"],
  "An electrical engineering lesson": ["technology", "code", "debug", "software", "update"],
  "Pikachu and Shankaracharya discuss advaita philosophy": ["truth", "mind", "self", "logic", "belief"],
  "Chaitanya expounds bhakti philosophy to a disciple": ["truth", "mind", "self", "logic", "belief"],
  "Two strangers have a conversation while walking out their dogs": ["dog", "walk", "leash", "pet", "bark"],
  "How to flirt in a bar?": ["flirt", "bar", "charm", "conversation", "smile"],
  "A baker explaining the recipe for a perfect sourdough bread": ["baker", "explaining", "recipe", "perfect", "sourdough"],
  "Discussing your favorite superhero at a comic book store": ["discussing", "your", "favorite", "superhero", "comic"],
  "A debate over whether cats or dogs make better pets": ["dog", "walk", "leash", "pet", "bark"],
  "Two friends planning a surprise birthday party": ["friends", "planning", "surprise", "birthday", "party"],
  "Discussing the plot of the latest blockbuster movie": ["discussing", "plot", "latest", "blockbuster", "movie"],
  "A student interviewing a veteran for a school project": ["questions", "answers", "job", "background", "experience"],
  "Two chefs arguing about the best way to cook pasta": ["chefs", "arguing", "about", "best", "cook"],
  "Ordering street food in a busy market": ["ordering", "street", "food", "busy", "market"],
  "A yoga instructor explaining the benefits of meditation": ["yoga", "instructor", "explaining", "benefits", "meditation"],
  "A job interview for a position as a zookeeper": ["questions", "answers", "job", "background", "experience"],
  "Two kids arguing over who gets to play the video game next": ["kids", "arguing", "over", "gets", "play"],
  "A tourist asking for directions to the museum": ["tourist", "asking", "directions", "museum", "word4"],
  "Buying a used car and discussing its features and price": ["buying", "used", "discussing", "features", "price"],
  "A librarian recommending books to a young reader": ["librarian", "recommending", "books", "young", "reader"],
  "An artist explaining their creative process at a gallery opening": ["artist", "explaining", "their", "creative", "process"],
  "Negotiating a raise with your boss": ["negotiating", "raise", "with", "your", "boss"],
  "A couple deciding on a name for their new puppy": ["couple", "deciding", "name", "their", "puppy"],
  "Discussing the merits of different coffee brews at a café": ["coffee", "order", "barista", "menu", "café"],
  "A scientist explaining climate change to a non-expert": ["scientist", "explaining", "climate", "change", "non-expert"],
  "A historical debate between Alexander the Great and a philosopher": ["historical", "debate", "between", "alexander", "great"],
  "A conversation at a bus stop about favorite travel destinations": ["conversation", "stop", "about", "favorite", "travel"],
  "Discussing the latest fashion trends and sustainable fashion": ["discussing", "latest", "fashion", "trends", "sustainable"],
  "A makeup tutorial for a glamorous party look": ["makeup", "tutorial", "glamorous", "party", "look"],
  "Two friends gossiping about a mutual acquaintance": ["friends", "gossiping", "about", "mutual", "acquaintance"],
  "A detective explaining how they solved a tricky case": ["detective", "explaining", "they", "solved", "tricky"],
  "A pilot describing the experience of flying to a curious passenger": ["pilot", "describing", "experience", "flying", "curious"],
  "Two gardeners sharing tips about organic gardening": ["gardeners", "sharing", "tips", "about", "organic"],
  "Planning a backpacking trip across Europe": ["planning", "backpacking", "trip", "across", "europe"],
  "A conversation between a vampire and a werewolf about nighttime routines": ["conversation", "between", "vampire", "werewolf", "about"],
  "A ghost giving a tour of a haunted house": ["ghost", "giving", "tour", "haunted", "house"],
  "Two friends debating the best pizza topping": ["friends", "debating", "best", "pizza", "topping"],
  "Discussing the benefits of different exercise routines at the gym": ["discussing", "benefits", "different", "exercise", "routines"],
  "A magical duel between two wizards, explaining their spells": ["magical", "duel", "between", "wizards,", "explaining"],
  "A bride and a wedding planner discussing decor themes": ["bride", "wedding", "planner", "discussing", "decor"],
  "Two children making up a story about a dragon and a princess": ["children", "making", "story", "about", "dragon"],
  "A critique session in an art class": ["critique", "session", "class", "word3", "word4"],
  "Discussing the rules of a new board game at a family game night": ["discussing", "rules", "board", "game", "family"],
  "Buying tickets at a train station": ["buying", "tickets", "train", "station", "word4"],
  "A fisherman telling tales of the one that got away": ["fisherman", "telling", "tales", "that", "away"],
  "A hairdresser explaining different haircuts to a client": ["hairdresser", "explaining", "different", "haircuts", "client"],
  "A coach giving a pep talk before a big game": ["coach", "giving", "talk", "before", "game"],
  "Two spies exchanging secret information in code": ["spies", "exchanging", "secret", "information", "code"],
  "Ordering a custom suit from a tailor": ["ordering", "custom", "suit", "from", "tailor"],
  "A conversation about the pros and cons of social media": ["conversation", "about", "pros", "cons", "social"],
  "Two seniors reminiscing about the 'good old days'": ["seniors", "reminiscing", "about", "good", "days"],
  "A debate about the best strategy for a zombie apocalypse": ["debate", "about", "best", "strategy", "zombie"],
  "Asking a neighbor to look after your plants while you're away": ["asking", "neighbor", "look", "after", "your"],
  "A poet reciting their latest work at an open mic night": ["poet", "reciting", "their", "latest", "work"],
  "Negotiating terms at a garage sale": ["negotiating", "terms", "garage", "sale", "word4"],
  "Two friends discussing the merits of different types of tea": ["friends", "discussing", "merits", "different", "types"],
  "Explaining the rules of cricket to a new player": ["explaining", "rules", "cricket", "player", "word4"],
  "A dentist explaining proper dental hygiene to a young child": ["dentist", "explaining", "proper", "dental", "hygiene"],
  "Two time travelers comparing notes on the best historical events": ["time", "travelers", "comparing", "notes", "best"],
  "A dietician giving advice on a healthy diet": ["dietician", "giving", "advice", "healthy", "diet"],
  "A mechanic explaining car maintenance to a first-time car owner": ["mechanic", "explaining", "maintenance", "first-time", "owner"],
  "Two musicians discussing the influence of classical music on modern genres": ["musicians", "discussing", "influence", "classical", "music"],
  "A conversation about the latest developments in space exploration": ["conversation", "about", "latest", "developments", "space"],
  "A real estate agent showcasing homes to potential buyers": ["real", "estate", "agent", "showcasing", "homes"],
  "Two philosophers debating the concept of free will": ["philosophers", "debating", "concept", "free", "will"],
  "Discussing different methods of learning a new language": ["discussing", "different", "methods", "learning", "language"],
  "A debate on the impact of technology on employment": ["debate", "impact", "technology", "employment", "word4"],
  "Two programmers arguing about the best programming language": ["programmers", "arguing", "about", "best", "programming"],
  "A first-time meeting between in-laws": ["first-time", "meeting", "between", "in-laws", "word4"],
  "A teenager explaining their favorite video game to their grandparent": ["teenager", "explaining", "their", "favorite", "video"],
  "A conversation between Shakespeare and a modern playwright": ["conversation", "between", "shakespeare", "modern", "playwright"],
  "A tourist bargaining at a local craft market": ["tourist", "bargaining", "local", "craft", "market"],
  "Two friends making plans for New Year's Eve": ["friends", "making", "plans", "year's", "word4"],
  "Discussing the plot twists of a popular TV show": ["discussing", "plot", "twists", "popular", "show"],
  "A cashier and a shopper discussing the benefits of loyalty cards": ["cashier", "shopper", "discussing", "benefits", "loyalty"],
  "A conversation about the ethical implications of artificial intelligence": ["conversation", "about", "ethical", "implications", "artificial"],
  "A safety briefing before a scuba diving session": ["safety", "briefing", "before", "scuba", "diving"],
  "Two kids planning their dream treehouse": ["kids", "planning", "their", "dream", "treehouse"],
  "A discussion about the best approaches to sustainable living": ["discussion", "about", "best", "approaches", "sustainable"],
  "A conversation on the best strategies for online learning": ["conversation", "best", "strategies", "online", "learning"],
  "Two neighbors arguing about lawn care": ["neighbors", "arguing", "about", "lawn", "care"],
  "A coach explaining the importance of teamwork to young athletes": ["coach", "explaining", "importance", "teamwork", "young"],
  "Planning a vegan dinner party menu": ["planning", "vegan", "dinner", "party", "menu"],
  "Two mountaineers discussing their next climb": ["mountaineers", "discussing", "their", "next", "climb"],
  "A conversation about the impact of global warming on small islands": ["conversation", "about", "impact", "global", "warming"],
  "Two friends comparing notes on gardening successes and failures": ["friends", "comparing", "notes", "gardening", "successes"],
  "A fitness trainer motivating a client during a workout": ["fitness", "trainer", "motivating", "client", "during"],
  "Discussing the best foods to try in Italy": ["discussing", "best", "foods", "italy", "word4"],
  "A historian explaining the significance of an ancient artifact": ["historian", "explaining", "significance", "ancient", "artifact"],
  "A conservationist talking about the importance of protecting endangered species": ["conservationist", "talking", "about", "importance", "protecting"],
  "Two friends planning a road trip across the United States": ["friends", "planning", "road", "trip", "across"],
  "A conversation between a mermaid and a sailor about ocean life": ["conversation", "between", "mermaid", "sailor", "about"],
  "Two colleagues discussing how to balance work and personal life": ["colleagues", "discussing", "balance", "work", "personal"],
  "A discussion on the pros and cons of electric vehicles": ["discussion", "pros", "cons", "electric", "vehicles"],
  "Two friends debating the best comic book character": ["friends", "debating", "best", "comic", "book"],
  "A tour guide explaining the history of a famous landmark": ["tour", "guide", "explaining", "history", "famous"],
  "Discussing the benefits and challenges of homeschooling": ["discussing", "benefits", "challenges", "homeschooling", "word4"],
  "A baker and a chef competing in a dessert-making contest": ["baker", "chef", "competing", "dessert-making", "contest"],
  "A discussion about the future of renewable energy sources": ["discussion", "about", "future", "renewable", "energy"],
  "Two grandparents talking about their grandchildren's antics": ["grandparents", "talking", "about", "their", "grandchildren's"],
  "A conversation about how to start a blog": ["conversation", "about", "start", "blog", "word4"],
  "Planning a picnic in the local park": ["planning", "picnic", "local", "park", "word4"],
  "Discussing the cultural significance of traditional dances": ["discussing", "cultural", "significance", "traditional", "dances"],
  "Two friends talking about their experiences at a music festival": ["friends", "talking", "about", "their", "experiences"],
  "A beekeeper explaining the process of honey production": ["beekeeper", "explaining", "process", "honey", "production"],
  "A conversation between an alien and an astronaut about space travel": ["conversation", "between", "alien", "astronaut", "about"],
  "A snail gives life advice to a rushing businessman.": ["snail", "advice", "life", "rush", "slow"],
  "A cat and a Buddhist monk meditate together under a tree.": ["cat", "monk", "meditate", "tree", "peace"],
  "A robot barista discusses existentialism with a lonely poet.": ["robot", "barista", "existentialism", "poet", "lonely"],
  "A toddler negotiates bedtime terms like a lawyer.": ["toddler", "bedtime", "negotiate", "lawyer", "rules"],
  "Two witches argue about whose broom is faster.": ["witch", "broom", "fast", "argue", "magic"],
  "A raccoon teaches a raccoon etiquette class on garbage bin behavior.": ["raccoon", "etiquette", "garbage", "class", "behavior"],
  "A caveman tries to understand how a smartphone works.": ["caveman", "smartphone", "understand", "technology", "confused"],
  "Two introverts silently bond while waiting for a delayed train.": ["introverts", "bond", "silence", "train", "delay"],
  "A mushroom explains forest gossip to a curious squirrel.": ["mushroom", "forest", "gossip", "squirrel", "curious"],
  "A werewolf starts a podcast about moonlight skincare.": ["werewolf", "podcast", "moonlight", "skincare", "routine"],
  "A pirate and a modern-day banker compare treasure-hunting methods.": ["pirate", "banker", "treasure", "compare", "methods"],
  "Two parrots eavesdrop and analyze human conversations.": ["parrots", "eavesdrop", "conversation", "analyze", "human"],
  "A fairy teaches a self-help seminar for burned-out magical creatures.": ["fairy", "self-help", "seminar", "burnout", "magic"],
  "An AI therapist counsels a heartbroken toaster.": ["AI", "therapist", "toaster", "heartbreak", "counsel"],
  "A bored ghost takes a dance class to feel alive.": ["ghost", "dance", "class", "alive", "bored"],
  "A philosopher gets stuck in an escape room with a toddler.": ["philosopher", "escape", "room", "toddler", "puzzle"],
  "Two potatoes discuss their fear of becoming fries.": ["potatoes", "fear", "fries", "kitchen", "fate"],
  "A barista starts interpreting dreams through latte foam patterns.": ["barista", "dreams", "latte", "foam", "interpret"],
  "A garden gnome leads a revolution in a suburban backyard.": ["gnome", "revolution", "suburban", "backyard", "lead"],
  "A stand-up comedian bombards aliens with Earth jokes.": ["comedian", "aliens", "earth", "jokes", "stand-up"],
  "A dragon and a climate scientist talk about global warming.": ["dragon", "climate", "warming", "talk", "scientist"],
  "A dog runs for mayor of a small town.": ["dog", "mayor", "election", "town", "campaign"],
  "A mime teaches communication skills to customer service reps.": ["mime", "communication", "skills", "customer", "service"],
  "Two bored AI assistants chat while their users sleep.": ["AI", "assistants", "chat", "bored", "sleep"],
  "A snowman gives dating advice before melting.": ["snowman", "dating", "advice", "melting", "relationship"],
  "A tea leaf reader explains a breakup using only metaphors.": ["tea", "reader", "breakup", "metaphor", "fortune"],
  "A sloth runs a productivity workshop.": ["sloth", "productivity", "workshop", "slow", "focus"],
  "Two magicians swap failed spell stories.": ["magicians", "spells", "fail", "stories", "magic"],
  "A pigeon holds a TED talk on urban survival.": ["pigeon", "TED", "urban", "survival", "talk"],
  "A cactus writes a lonely heart column.": ["cactus", "lonely", "column", "heart", "write"],
  "Two kids build a spaceship from cardboard and take imaginary flight.": ["kids", "spaceship", "cardboard", "imagine", "fly"],
  "An alien disguised as a tourist asks deep questions at a souvenir shop.": ["alien", "tourist", "questions", "souvenir", "shop"],
  "A linguist and a caveman try to co-write a dictionary.": ["linguist", "caveman", "dictionary", "write", "language"],
  "A jellyfish explains ocean politics to a visiting dolphin.": ["jellyfish", "ocean", "politics", "dolphin", "talk"],
  "A travel blogger interviews a hermit about life off the grid.": ["blogger", "hermit", "travel", "interview", "off-grid"],
  "A vampire opens a vegan smoothie bar.": ["vampire", "vegan", "smoothie", "bar", "open"],
  "A retired superhero gives a motivational speech at a high school.": ["superhero", "motivational", "speech", "school", "retired"],
  "A squirrel starts an acorn-based economy.": ["squirrel", "acorn", "economy", "start", "forest"],
  "A therapist and their inner child go on a road trip.": ["therapist", "inner", "child", "road", "trip"],
  "A time traveler argues with a medieval farmer about crop rotation.": ["time", "traveler", "medieval", "farmer", "crops"],
  "A crow critiques modern architecture.": ["crow", "critique", "architecture", "modern", "design"],
  "A haunted house asks a ghost to move out for being “too loud.”": ["haunted", "house", "ghost", "loud", "move"],
  "A magician runs for local office on a “no secrets” campaign.": ["magician", "office", "secrets", "campaign", "vote"],
  "A baby gives a TED talk on the power of naps.": ["baby", "TED", "naps", "power", "talk"],
  "A UFO gets pulled over by intergalactic police.": ["UFO", "police", "space", "intergalactic", "law"],
  "A plant gives silent judgment to its overwatering owner.": ["plant", "judgment", "water", "owner", "care"],
  "A frog starts a jazz band in the swamp.": ["frog", "jazz", "band", "swamp", "music"],
  "A philosopher penguin questions the meaning of waddling.": ["penguin", "philosopher", "waddle", "meaning", "walk"],
  "A jellybean seeks therapy for identity issues.": ["jellybean", "therapy", "identity", "candy", "issues"],
  "A comet hosts a podcast about cosmic drama.": ["comet", "podcast", "cosmic", "drama", "space"],
  "A knight in full armor struggles through airport security.": ["knight", "armor", "airport", "security", "metal"],
  "A detective snail investigates a missing lettuce leaf.": ["snail", "detective", "lettuce", "missing", "investigate"],
  "A librarian bans noisy ghosts from whispering too loudly.": ["librarian", "ghosts", "whisper", "noisy", "library"],
  "A group of emojis go to therapy to deal with overuse.": ["emojis", "therapy", "communication", "overuse", "symbols"],
  "A fortune cookie tries to rewrite its own destiny.": ["fortune", "cookie", "destiny", "rewrite", "future"],
  "Two emojis fall in love during an autocorrect glitch.": ["emoji", "love", "autocorrect", "glitch", "text"],
  "A toaster develops a passion for haiku.": ["toaster", "haiku", "poetry", "burnt", "passion"],
  "A centaur applies for a car loan.": ["centaur", "loan", "car", "bank", "application"],
  "A chef teaches aliens how to use salt.": ["chef", "aliens", "salt", "cooking", "teaching"],
  "A bored candle starts blogging about wax politics.": ["candle", "blog", "wax", "bored", "politics"],
  "A dinosaur tries to blend in at a modern dog park.": ["dinosaur", "dog", "park", "blend", "modern"],
  "A vampire and a dentist meet at a blood donation center.": ["vampire", "dentist", "blood", "teeth", "meeting"],
  "A pirate joins a startup accelerator.": ["pirate", "startup", "accelerator", "business", "venture"],
  "A cactus and a bonsai debate the nature of growth.": ["cactus", "bonsai", "debate", "growth", "nature"],
  "A cloud contemplates retiring after too many thunderstorms.": ["cloud", "retire", "storm", "weather", "tired"],
  "A philosopher and a stand-up comic trade places for a day.": ["philosopher", "comic", "swap", "ideas", "laughter"],
  "A delivery drone questions its purpose mid-flight.": ["drone", "delivery", "existence", "flight", "purpose"],
  "A group of emojis unionize.": ["emojis", "union", "rights", "chat", "negotiation"],
  "A genie opens a small business consultancy.": ["genie", "business", "consultancy", "wish", "strategy"],
  "A therapist tries to mediate a love triangle between sun, moon, and Earth.": ["therapist", "love", "sun", "moon", "earth"],
  "A chameleon has an identity crisis in a mirror maze.": ["chameleon", "identity", "mirror", "maze", "colors"],
  "A snail enters a Formula 1 race as a metaphor.": ["snail", "race", "formula", "speed", "metaphor"],
  "A spreadsheet becomes self-aware and deletes itself.": ["spreadsheet", "data", "aware", "delete", "logic"],
  "A robot joins a knitting circle.": ["robot", "knitting", "circle", "hobby", "craft"],
  "A calendar gets overwhelmed by existential dread.": ["calendar", "dates", "existence", "time", "overwhelm"],
  "A starfish runs for ocean council presidency.": ["starfish", "election", "ocean", "president", "council"],
  "A dandelion philosophizes on impermanence.": ["dandelion", "philosophy", "impermanence", "nature", "life"],
  "A ghost tries to sign a lease.": ["ghost", "lease", "apartment", "rent", "haunted"],
  "A squirrel creates an anti-nut manifesto.": ["squirrel", "nuts", "manifesto", "protest", "forest"],
  "A fish enrolls in flying lessons.": ["fish", "fly", "lessons", "dream", "sky"],
  "A sentient Roomba reflects on its life’s purpose.": ["roomba", "purpose", "cleaning", "existence", "thought"],
  "A loaf of bread narrates its transformation journey.": ["bread", "journey", "bake", "flour", "life"],
  "A pigeon complains about gentrification in the park.": ["pigeon", "gentrification", "park", "complaint", "city"],
  "A lava lamp discusses mood with a psychologist.": ["lava", "lamp", "mood", "psychologist", "flow"],
  "A werewolf interviews for a job in corporate.": ["werewolf", "interview", "job", "corporate", "moon"],
  "A snail wins a reality show and doesn’t know what to do next.": ["snail", "reality", "show", "fame", "confused"],
  "A jellyfish opens a floatation therapy center.": ["jellyfish", "float", "therapy", "relax", "ocean"],
  "A rainbow talks about its emotional spectrum.": ["rainbow", "emotion", "spectrum", "colors", "feelings"],
  "A vending machine starts a support group for neglected machines.": ["vending", "machine", "support", "neglect", "group"],
  "A philosophical sandwich questions its layers.": ["sandwich", "philosophy", "layers", "meaning", "hunger"],
  "An umbrella files a lawsuit against the weather.": ["umbrella", "lawsuit", "weather", "rain", "rights"],
  "A piece of tofu contemplates its blandness.": ["tofu", "bland", "flavor", "identity", "food"],
  "A lamp gives relationship advice based on shadow interpretation.": ["lamp", "shadow", "advice", "light", "relationship"],
  "A piece of spaghetti escapes the pot and starts a blog.": ["spaghetti", "escape", "pot", "blog", "adventure"],
  "A calendar rebels and deletes Monday.": ["calendar", "monday", "delete", "rebel", "schedule"],
  "A parrot becomes a life coach.": ["parrot", "life", "coach", "talk", "advice"],
  "A puppet cuts its strings and starts stand-up comedy.": ["puppet", "freedom", "comedy", "stage", "jokes"],
  "A moon rock writes poetry about Earth.": ["moon", "rock", "poetry", "earth", "distance"],
  "A mushroom advocates for introvert rights at a forest council.": ["mushroom", "introvert", "rights", "forest", "speak"],
  "A robot starts dreaming and tries to describe it to humans.": ["robot", "dream", "describe", "human", "sleep"],
  "A scarecrow goes on a date with a pumpkin.": ["scarecrow", "pumpkin", "date", "farm", "autumn"],
  "A jellyfish becomes a fashion influencer underwater.": ["jellyfish", "fashion", "influencer", "underwater", "style"],
  "A robot chef accidentally invents a new flavor of sadness.": ["robot", "chef", "flavor", "sadness", "invent"],
  "A goose gives motivational speeches at a lakeside retreat.": ["goose", "motivational", "speech", "lake", "retreat"],
  "A time-traveling sandwich solves ancient mysteries.": ["sandwich", "time", "travel", "mystery", "history"],
  "A fridge starts a podcast about leftovers.": ["fridge", "podcast", "leftovers", "kitchen", "stories"],
  "A hippo teaches ballet in a muddy swamp.": ["hippo", "ballet", "swamp", "dance", "lesson"],
  "A moonbeam falls in love with a puddle.": ["moonbeam", "love", "puddle", "light", "reflection"],
  "A cactus wins a spelling bee in the desert.": ["cactus", "spelling", "bee", "desert", "competition"],
  "A raccoon becomes obsessed with abstract art.": ["raccoon", "art", "abstract", "obsessed", "gallery"],
  "A pencil writes its autobiography.": ["pencil", "write", "autobiography", "story", "eraser"],
  "A butterfly runs for student council in a bug school.": ["butterfly", "school", "council", "election", "bug"],
  "A star learns to juggle planets.": ["star", "juggle", "planet", "space", "balance"],
  "A lonely sock writes poetry to its missing pair.": ["sock", "poetry", "lonely", "pair", "laundry"],
  "A haunted teapot gives out unsolicited advice.": ["teapot", "haunted", "advice", "kitchen", "ghost"],
  "A marshmallow finds enlightenment during a campfire.": ["marshmallow", "campfire", "enlightenment", "toast", "wisdom"],
  "A dragonfly teaches mindfulness to bees.": ["dragonfly", "mindfulness", "bees", "focus", "buzz"],
  "A banana wins a karaoke contest.": ["banana", "karaoke", "contest", "sing", "fruit"],
  "A sandcastle declares independence.": ["sandcastle", "independence", "beach", "rule", "wave"],
  "A piece of lint starts a detective agency.": ["lint", "detective", "agency", "small", "mystery"],
  "A snail becomes a DJ at a forest rave.": ["snail", "DJ", "rave", "music", "forest"],
  "A telescope gives romantic advice to stars.": ["telescope", "stars", "romantic", "sky", "advice"],
  "A crayon leads a rebellion against coloring books.": ["crayon", "rebellion", "coloring", "book", "draw"],
  "A cookie refuses to be eaten and goes on strike.": ["cookie", "strike", "eaten", "bake", "demand"],
  "A peanut butter jar runs for president of the fridge.": ["peanut", "butter", "president", "fridge", "campaign"],
  "A rubber duck trains to become a lifeguard.": ["duck", "rubber", "lifeguard", "pool", "float"],
  "A vacuum cleaner starts a band with a blender.": ["vacuum", "blender", "band", "music", "noise"],
  "A bowtie reflects on its identity at a black-tie event.": ["bowtie", "identity", "event", "reflection", "formal"],
  "A firefly opens a tiny bookstore in a lantern.": ["firefly", "bookstore", "tiny", "lantern", "read"],
  "A toaster competes in an international gymnastics event.": ["toaster", "gymnastics", "competition", "flip", "balance"],
  "A puddle writes a memoir about rainy days.": ["puddle", "memoir", "rain", "day", "reflection"],
  "A shoelace becomes a philosopher.": ["shoelace", "philosopher", "loop", "knot", "question"],
  "A teddy bear hosts a late-night talk show.": ["teddy", "bear", "talk", "show", "night"],
  "A gnome opens a tech startup in a tree stump.": ["gnome", "startup", "tech", "tree", "stump"],
  "A piece of cheese trains in martial arts.": ["cheese", "martial", "arts", "train", "slice"],
  "A key loses its door and goes on a journey of self-discovery.": ["key", "door", "lost", "journey", "identity"],
  "A weather vane writes daily affirmations.": ["vane", "weather", "affirmation", "daily", "wind"],
  "A penguin becomes a wine sommelier.": ["penguin", "wine", "sommelier", "taste", "class"],
  "A calculator starts questioning math.": ["calculator", "math", "question", "logic", "doubt"],
  "A mop takes salsa dance classes.": ["mop", "salsa", "dance", "class", "clean"],
  "A snowflake delivers motivational speeches before melting.": ["snowflake", "speech", "melt", "unique", "moment"],
  "A pot of honey writes a love letter to a pancake.": ["honey", "pancake", "love", "letter", "sweet"],
  "A broomstick joins a punk rock band.": ["broomstick", "punk", "band", "rock", "music"],
  "A spoon gets promoted to fork.": ["spoon", "fork", "promotion", "cutlery", "change"],
  "A lightbulb starts an idea farm.": ["lightbulb", "idea", "farm", "grow", "spark"],
  "A curtain sings opera when no one is home.": ["curtain", "opera", "sing", "house", "secret"],
  "A beanbag explores its purpose beyond sitting.": ["beanbag", "purpose", "comfort", "existence", "furniture"],
  "A calculator joins a philosophy club.": ["calculator", "philosophy", "logic", "club", "questions"],
  "A flame falls in love with a snowflake.": ["flame", "snowflake", "love", "opposite", "melt"],
  "A traffic cone writes inspirational quotes in chalk.": ["cone", "traffic", "quotes", "chalk", "street"],
  "A slice of toast runs a startup incubator for jam.": ["toast", "startup", "jam", "incubator", "breakfast"],
  "A pencil sharpener holds a philosophy debate with a stapler.": ["sharpener", "stapler", "debate", "philosophy", "office"],
  "A moonbeam starts a jazz club inside a telescope.": ["moonbeam", "jazz", "club", "telescope", "music"],
  "A snow globe hosts a reality TV show for miniature figurines.": ["snow globe", "reality", "TV", "miniature", "show"],
  "A calendar gives TED talks about time management.": ["calendar", "TED", "talks", "time", "management"],
  "A jellyfish becomes the CEO of a deep-sea tech firm.": ["jellyfish", "CEO", "tech", "deep-sea", "startup"],
  "A teacup has an identity crisis after being mistaken for a mug.": ["teacup", "mug", "identity", "crisis", "confusion"],
  "A bubble starts a movement for temporary beauty.": ["bubble", "beauty", "temporary", "movement", "pop"],
  "A ukulele teaches music theory to crabs.": ["ukulele", "music", "theory", "crabs", "lesson"],
  "A dandelion starts a mindfulness app for weeds.": ["dandelion", "mindfulness", "app", "weeds", "calm"],
  "A shoelace unionizes against tight knots.": ["shoelace", "union", "tight", "knots", "strike"],
  "A fish becomes a meditation coach for stressed sharks.": ["fish", "coach", "meditation", "sharks", "stress"],
  "A candle hosts a workshop on burning brightly without burnout.": ["candle", "burnout", "bright", "workshop", "energy"],
  "A paintbrush falls in love with an empty canvas.": ["paintbrush", "canvas", "love", "art", "create"],
  "A pair of sunglasses hosts a podcast on seeing clearly.": ["sunglasses", "podcast", "clarity", "vision", "see"],
  "A peanut starts a book club for allergic animals.": ["peanut", "book", "club", "allergy", "animals"],
  "A whisk writes a novel about life in a mixing bowl.": ["whisk", "novel", "mix", "bowl", "life"],
  "A wind chime teaches sound design to owls.": ["wind", "chime", "sound", "design", "owl"],
  "A pair of flip-flops goes on a pilgrimage to find purpose.": ["flip-flops", "pilgrimage", "purpose", "feet", "journey"],
  "A paperclip opens a museum of forgotten notes.": ["paperclip", "museum", "notes", "forgotten", "exhibit"],
  "A storm cloud takes anger management classes.": ["cloud", "storm", "anger", "class", "emotions"],
  "A flashlight sings lullabies to lost campers.": ["flashlight", "lullaby", "campers", "light", "forest"],
  "A notebook starts journaling its own pages.": ["notebook", "journal", "write", "pages", "reflection"],
  "A cup of tea attends a silent retreat.": ["tea", "retreat", "silent", "calm", "steep"],
  "A plug and socket get married in an electric ceremony.": ["plug", "socket", "marriage", "electric", "connection"],
  "A turtle opens a mindfulness dojo for fast animals.": ["turtle", "dojo", "mindfulness", "fast", "animals"],
  "A band-aid hosts a healing circle.": ["band-aid", "healing", "circle", "pain", "care"],
  "A rock starts a poetry zine.": ["rock", "poetry", "zine", "write", "nature"],
  "A spider opens a design agency for webs.": ["spider", "design", "web", "agency", "creative"],
  "A snow shovel goes to therapy to process winter trauma.": ["shovel", "snow", "therapy", "trauma", "winter"],
  "A marshmallow joins a fitness bootcamp.": ["marshmallow", "fitness", "bootcamp", "soft", "strength"],
  "A pair of mittens opens a matchmaking service for lonely hands.": ["mittens", "matchmaking", "hands", "love", "pair"],
  "A mirror develops stage fright.": ["mirror", "reflection", "stage", "fright", "shy"],
  "A pancake hosts a brunch talk on softness and strength.": ["pancake", "brunch", "talk", "soft", "strength"],
  "A sand grain dreams of becoming a mountain.": ["sand", "grain", "mountain", "dream", "grow"],
  "A window argues with the wall about perspective.": ["window", "wall", "perspective", "view", "argue"],
  "A kite opens a flight school for paper planes.": ["kite", "flight", "school", "paper", "sky"],
  "A blanket starts a comfort hotline.": ["blanket", "comfort", "hotline", "warm", "call"],
  "A jelly jar writes breakup letters to its lid.": ["jar", "jelly", "lid", "breakup", "letter"],
  "A cloud of dust narrates the history of the bookshelf.": ["dust", "history", "bookshelf", "narrate", "quiet"],
  "A measuring tape has an existential crisis.": ["measuring", "tape", "existence", "length", "crisis"],
  "A light switch develops a fear of commitment.": ["light", "switch", "fear", "commitment", "on-off"],
  "A cupholder teaches a course on holding space.": ["cupholder", "course", "space", "hold", "support"],
  "A backpack hosts a summit for objects with emotional baggage.": ["backpack", "summit", "baggage", "object", "carry"],
  "A flame teaches a class on passion and boundaries.": ["flame", "passion", "boundaries", "fire", "teach"],
  "A doormat gives lectures on humility.": ["doormat", "humility", "lecture", "step", "home"],
  "A closet reflects on the skeletons it’s hiding.": ["closet", "skeletons", "secrets", "reflect", "hidden"],
  "A mirrorball starts a memoir about life under the spotlight.": ["mirrorball", "memoir", "spotlight", "disco", "life"],
  "A pair of chopsticks tries to stay together during a breakup.": ["chopsticks", "breakup", "together", "pair", "separate"],
  "A staircase starts a motivational seminar called 'Step by Step'.": ["staircase", "steps", "motivation", "seminar", "climb"],
  "A teenager and their grandmother bond over baking cookies": ["teenager", "grandmother", "baking", "cookies", "bond"],
  "A couple discusses adopting a rescue dog at the shelter": ["couple", "adopting", "rescue", "dog", "shelter"],
  "Two coworkers share productivity tips over lunch": ["coworkers", "productivity", "tips", "lunch", "work"],
  "A teacher organizes a surprise farewell party for a student": ["teacher", "farewell", "party", "student", "surprise"],
  "Friends debate where to go on their next weekend trip": ["friends", "debate", "trip", "weekend", "plan"],
  "A new neighbor is welcomed with a homemade cake": ["neighbor", "welcomed", "cake", "homemade", "community"],
  "A fitness trainer introduces a beginner to yoga": ["fitness", "trainer", "yoga", "beginner", "lesson"],
  "Two students cram for an exam at the library": ["students", "exam", "library", "study", "cram"],
  "A barista explains the difference between espresso and latte": ["barista", "espresso", "latte", "difference", "coffee"],
  "A couple learns how to salsa dance at a class": ["couple", "salsa", "dance", "class", "learn"],
  "A child tries to convince their parent to adopt a kitten": ["child", "parent", "kitten", "adopt", "convince"],
  "Two travelers trade language tips at a hostel": ["travelers", "language", "tips", "hostel", "conversation"],
  "An old friend visits unexpectedly and catches up over tea": ["friend", "visit", "unexpectedly", "tea", "catch"],
  "Siblings prepare a surprise breakfast for their parents": ["siblings", "breakfast", "surprise", "parents", "prepare"],
  "A retiree teaches painting at a community center": ["retiree", "painting", "teach", "community", "center"],
  "Two roommates argue about household chores": ["roommates", "argue", "chores", "household", "clean"],
  "A babysitter entertains kids with a treasure hunt": ["babysitter", "kids", "treasure", "hunt", "entertain"],
  "A friend helps another prepare for a job interview": ["friend", "help", "job", "interview", "prepare"],
  "A couple plants a small herb garden on their balcony": ["couple", "herb", "garden", "balcony", "plant"],
  "A dentist calms a nervous child before a checkup": ["dentist", "nervous", "child", "checkup", "calm"],
  "A bus driver greets each passenger with a smile": ["bus", "driver", "greet", "passenger", "smile"],
  "A family chooses toppings for homemade pizza night": ["family", "pizza", "toppings", "homemade", "night"],
  "Friends try indoor climbing for the first time": ["friends", "climbing", "indoor", "first", "time"],
  "A bar owner hosts open mic poetry nights": ["bar", "owner", "mic", "poetry", "nights"],
  "Two artists sketch each other at a cafe": ["artists", "sketch", "cafe", "draw", "each"],
  "A hairdresser chats with a customer about travel plans": ["hairdresser", "customer", "travel", "plans", "chat"],
  "A pair of grandparents take selfies with their grandchild": ["grandparents", "selfies", "grandchild", "family", "photos"],
  "A dog walker juggles five enthusiastic pups": ["dog", "walker", "pups", "enthusiastic", "juggle"],
  "Two gamers team up to defeat a difficult boss": ["gamers", "team", "boss", "defeat", "game"],
  "A music teacher helps a student learn violin": ["music", "teacher", "student", "violin", "lesson"],
  "A couple gets lost in a maze and laughs it off": ["couple", "maze", "lost", "laugh", "navigate"],
  "A teenager films a cooking tutorial for social media": ["teenager", "cooking", "tutorial", "social", "media"],
  "Two friends host a trivia night at a pub": ["friends", "trivia", "pub", "host", "night"],
  "A florist teaches flower arranging to kids": ["florist", "flower", "arranging", "teach", "kids"],
  "A street musician performs during the evening rush": ["musician", "street", "evening", "rush", "perform"],
  "A local bookstore organizes a reading for children": ["bookstore", "reading", "children", "organize", "local"],
  "A baker hosts a sourdough workshop": ["baker", "sourdough", "workshop", "bread", "teach"],
  "Two tourists ask for vegetarian options at a restaurant": ["tourists", "vegetarian", "restaurant", "ask", "options"],
  "A wedding planner helps with last-minute flower troubles": ["wedding", "planner", "flower", "last-minute", "help"],
  "An aunt and niece bake cupcakes for a school sale": ["aunt", "niece", "cupcakes", "bake", "school"],
  "A cycling group plans their next scenic route": ["cycling", "group", "route", "plan", "scenic"],
  "A dog barks at its own reflection in a puddle": ["dog", "bark", "reflection", "puddle", "funny"],
  "A young chef competes in a cooking show for teens": ["chef", "cooking", "teens", "show", "compete"],
  "A couple debates furniture choices for their first apartment": ["couple", "furniture", "apartment", "debate", "choices"],
  "A volunteer delivers meals to elderly neighbors": ["volunteer", "meals", "elderly", "neighbors", "deliver"],
  "Two friends get matching temporary tattoos": ["friends", "tattoos", "matching", "temporary", "fun"],
  "A classmate helps another understand a math problem": ["classmate", "math", "problem", "help", "understand"],
  "A tourist rents a bike and explores a European city": ["tourist", "bike", "rent", "city", "explore"],
  "A grandma tells bedtime stories to her grandchildren": ["grandma", "bedtime", "stories", "grandchildren", "tell"]
};
