List<String> example_scenarios = [
  "Einstein has a philosophical conversation about life with a duckling.",
  "Ordering a coffee",
  "A conversation between 2 product managers about compliance and GDPR",
  "Two software engineers discuss the latest advancements in AI",
  "A conversation between a product manager and a software engineer",
  "An electrical engineering lesson",
  "Pikachu and Shankaracharya discuss advaita philosophy",
  "Chaitanya expounds bhakti philosophy to a disciple",
  "Two strangers have a conversation while walking out their dogs",
  "How to flirt in a bar?",
  "A baker explaining the recipe for a perfect sourdough bread",
  "Discussing your favorite superhero at a comic book store",
  "A debate over whether cats or dogs make better pets",
  "Two friends planning a surprise birthday party",
  "Discussing the plot of the latest blockbuster movie",
  "A student interviewing a veteran for a school project",
  "Two chefs arguing about the best way to cook pasta",
  "Ordering street food in a busy market",
  "A yoga instructor explaining the benefits of meditation",
  "A job interview for a position as a zookeeper",
  "Two kids arguing over who gets to play the video game next",
  "A tourist asking for directions to the museum",
  "Buying a used car and discussing its features and price",
  "A librarian recommending books to a young reader",
  "An artist explaining their creative process at a gallery opening",
  "Negotiating a raise with your boss",
  "A couple deciding on a name for their new puppy",
  "Discussing the merits of different coffee brews at a café",
  "A scientist explaining climate change to a non-expert",
  "A historical debate between Alexander the Great and a philosopher",
  "A conversation at a bus stop about favorite travel destinations",
  "Discussing the latest fashion trends and sustainable fashion",
  "A makeup tutorial for a glamorous party look",
  "Two friends gossiping about a mutual acquaintance",
  "A detective explaining how they solved a tricky case",
  "A pilot describing the experience of flying to a curious passenger",
  "Two gardeners sharing tips about organic gardening",
  "Planning a backpacking trip across Europe",
  "A conversation between a vampire and a werewolf about nighttime routines",
  "A ghost giving a tour of a haunted house",
  "Two friends debating the best pizza topping",
  "Discussing the benefits of different exercise routines at the gym",
  "A magical duel between two wizards, explaining their spells",
  "A bride and a wedding planner discussing decor themes",
  "Two children making up a story about a dragon and a princess",
  "A critique session in an art class",
  "Discussing the rules of a new board game at a family game night",
  "Buying tickets at a train station",
  "A fisherman telling tales of the one that got away",
  "A hairdresser explaining different haircuts to a client",
  "A coach giving a pep talk before a big game",
  "Two spies exchanging secret information in code",
  "Ordering a custom suit from a tailor",
  "A conversation about the pros and cons of social media",
  "Two seniors reminiscing about the \"good old days\"",
  "A debate about the best strategy for a zombie apocalypse",
  "Asking a neighbor to look after your plants while you're away",
  "A poet reciting their latest work at an open mic night",
  "Negotiating terms at a garage sale",
  "Two friends discussing the merits of different types of tea",
  "Explaining the rules of cricket to a new player",
  "A dentist explaining proper dental hygiene to a young child",
  "Two time travelers comparing notes on the best historical events",
  "A dietician giving advice on a healthy diet",
  "A mechanic explaining car maintenance to a first-time car owner",
  "Two musicians discussing the influence of classical music on modern genres",
  "A conversation about the latest developments in space exploration",
  "A real estate agent showcasing homes to potential buyers",
  "Two philosophers debating the concept of free will",
  "Discussing different methods of learning a new language",
  "A debate on the impact of technology on employment",
  "Two programmers arguing about the best programming language",
  "A first-time meeting between in-laws",
  "A teenager explaining their favorite video game to their grandparent",
  "A conversation between Shakespeare and a modern playwright",
  "A tourist bargaining at a local craft market",
  "Two friends making plans for New Year's Eve",
  "Discussing the plot twists of a popular TV show",
  "A cashier and a shopper discussing the benefits of loyalty cards",
  "A conversation about the ethical implications of artificial intelligence",
  "A safety briefing before a scuba diving session",
  "Two kids planning their dream treehouse",
  "A discussion about the best approaches to sustainable living",
  "A conversation on the best strategies for online learning",
  "Two neighbors arguing about lawn care",
  "A coach explaining the importance of teamwork to young athletes",
  "Planning a vegan dinner party menu",
  "Two mountaineers discussing their next climb",
  "A conversation about the impact of global warming on small islands",
  "Two friends comparing notes on gardening successes and failures",
  "A fitness trainer motivating a client during a workout",
  "Discussing the best foods to try in Italy",
  "A historian explaining the significance of an ancient artifact",
  "A conservationist talking about the importance of protecting endangered species",
  "Two friends planning a road trip across the United States",
  "A conversation between a mermaid and a sailor about ocean life",
  "Two colleagues discussing how to balance work and personal life",
  "A discussion on the pros and cons of electric vehicles",
  "Two friends debating the best comic book character",
  "A tour guide explaining the history of a famous landmark",
  "Discussing the benefits and challenges of homeschooling",
  "A baker and a chef competing in a dessert-making contest",
  "A discussion about the future of renewable energy sources",
  "Two grandparents talking about their grandchildren's antics",
  "A conversation about how to start a blog",
  "Planning a picnic in the local park",
  "Discussing the cultural significance of traditional dances",
  "Two friends talking about their experiences at a music festival",
  "A beekeeper explaining the process of honey production",
  "A conversation between an alien and an astronaut about space travel",
];
