const languageCodes = {
  "Afrikaans": "af-ZA",
  "Arabic": "ar-EG",
  "Azerbaijani": "az-AZ",
  "Bengali": "bn-IN",
  "Catalan": "ca-ES",
  "Chinese": "cmn-Hans-CN",
  "Chinese, Cantonese Hong": "yue-Hant-HK",
  "Danish": "da-DK",
  "Dutch": "nl-NL",
  "English": "en-US",
  "French": "fr-FR",
  "German": "de-DE",
  "Greek": "el-GR",
  "Hindi": "hi-IN",
  "Italian": "it-IT",
  "Japanese": "ja-JP",
  "Korean": "ko-KR",
  "Portuguese": "pt-BR",
  "Russian": "ru-RU",
  "Spanish": "es-MX",
  "Tamil": "ta-IN",
  "Turkish": "tr-TR",
  "Zulu": "zu-ZA"
};
