const greetingsList = {
  "English (US)": ["Hi, there!", "How's it going", "Hi", "Hi, there", "Good day"],
  "Arabic": ["مرحبا", "كيف الحال؟", "مرحبا", "مرحبا", "صباح الخير"],
  "Bengali": ["হ্যালো", "কেমন আছো?", "হ্যালো", "হ্যালো", "শুভ দিন"],
  "Danish": ["Hej", "Hvordan går det?", "Hej", "Hej, der", "God dag"],
  "English (Australia)": ["Hi", "How's it going", "Hi", "Hi, there", "Good day"],
  "English (UK)": ["Hi", "How's it going", "Hi", "Hi, there", "Good day"],
  "Filipino": ["Kamusta", "Kumusta?", "Kamusta", "Kamusta", "Mabuhay"],
  "French (Canada)": ["Bonjour", "Comment ça va?", "Salut", "Salut à toi", "Bonjour à toi"],
  "French (France)": ["Bonjour", "Comment ça va?", "Salut", "Salut à toi", "Bonjour à toi"],
  "Gujarati": ["સાંતાપણું", "તમે કેમ છો?", "સાંતાપણું", "સાંતાપણું", "શુભ દિવસ"],
  "Hindi": ["नमस्ते", "कैसे हैं?", "नमस्ते", "नमस्ते", "शुभ प्रभात"],
  "German": ["Hallo", "Wie geht's?", "Guten Tag", "Guten Tag, wie geht's?", "Grüezi"],
  "Indonesian": ["Halo", "Bagaimana khabar?", "Halo", "Halo", "Selamat pagi"],
  "Italian": ["Ciao", "Come stai?", "Salve", "Salve, come stai?", "Buongiorno"],
  "Japanese": ["こんにちは", "お元気ですか？", "こんにちは", "こんにちは", "おはようございます"],
  "Korean": ["안녕하세요", "어떻게 지내세요?", "안녕하세요", "안녕하세요", "좋은 아침이에요"],
  "Malay": ["Halo", "Bagaimana khabar?", "Halo", "Halo", "Selamat pagi"],
  "Mandarin Chinese": ["你好", "你好嗎？", "你好", "你好", "早上好"],
  "Norwegian": ["Hei", "Hvordan går det?", "Hei", "Hei, der", "God dag"],
  "Polish": ["Cześć", "Jak się masz?", "Cześć", "Cześć", "Dzień dobry"],
  "Portuguese (Brazil)": ["Olá", "Como vai?", "Olá", "Olá", "Bom dia"],
  "Portuguese (Portugal)": ["Olá", "Como vai?", "Olá", "Olá", "Bom dia"],
  "Russian": ["Привет", "Как дела?", "Привет", "Привет", "Доброе утро"],
  "Spanish (Spain)": ["Hola", "¿Cómo estás?", "¿Qué tal?", "¿Qué hay?", "Buenos días"],
  "Spanish (Mexico)": ["Hola", "¿Cómo estás?", "¿Qué tal?", "¿Qué hay?", "Buenos días"],
  "Swedish": ["Hej", "Hur mår du?", "Hej", "Hej, der", "God dag"],
  "Tamil": ["வணக்கம்", "எப்படி இருக்கிறீர்கள்?", "வணக்கம்", "வணக்கம்", "நன்றி"],
  "Turkish": ["Merhaba", "Nasıl gidiyor?", "Merhaba", "Merhaba", "Günaydın"],
  "Vietnamese": ["Xin chào", "Bạn thế nào?", "Xin chào", "Xin chào", "Chào buổi sáng"],
};
