const greetingsList = {
  "English (US)": ["Hi, there!", "How's it going?", "Hello!", "Good day!", "Hey!"],
  "Arabic": ["مرحبا", "كيف الحال؟", "صباح الخير", "مساء الخير", "أهلا"],
  "Bengali": ["হ্যালো", "কেমন আছো?", "শুভ দিন", "শুভ সকাল", "নমস্কার"],
  "Danish": ["Hej", "Hvordan går det?", "God dag", "Hej, der", "Goddag"],
  "English (Australia)": ["G'day!", "How's it going?", "Hello!", "Good day!", "Hey!"],
  "English (UK)": ["Hi!", "How's it going?", "Hello!", "Good day!", "Cheers!"],
  "Filipino": ["Kamusta", "Kumusta?", "Mabuhay", "Magandang araw", "Hello"],
  "French (Canada)": ["Bonjour", "Comment ça va?", "Salut", "Salut à toi", "Bon matin"],
  "French (France)": ["Bonjour", "Comment ça va?", "Salut", "Bonsoir", "Coucou"],
  "Gujarati": ["સાંતાપણું", "તમે કેમ છો?", "શુભ દિવસ", "નમસ્તે", "ગુડ મોર્નિંગ"],
  "Hindi": ["नमस्ते", "कैसे हैं?", "शुभ प्रभात", "नमस्कार", "हैलो"],
  "German": ["Hallo", "Wie geht's?", "Guten Tag", "Guten Morgen", "Grüß Gott"],
  "Indonesian": ["Halo", "Bagaimana kabar?", "Selamat pagi", "Selamat siang", "Apa kabar?"],
  "Italian": ["Ciao", "Come stai?", "Salve", "Buongiorno", "Buonasera"],
  "Japanese": ["こんにちは", "お元気ですか？", "おはようございます", "こんばんは", "やあ"],
  "Korean": ["안녕하세요", "어떻게 지내세요?", "좋은 아침이에요", "안녕", "반갑습니다"],
  "Malay": ["Halo", "Bagaimana khabar?", "Selamat pagi", "Selamat petang", "Apa khabar?"],
  "Mandarin Chinese": ["你好", "你好嗎？", "早上好", "晚上好", "嗨"],
  "Norwegian": ["Hei", "Hvordan går det?", "God dag", "Hei, der", "God morgen"],
  "Polish": ["Cześć", "Jak się masz?", "Dzień dobry", "Witaj", "Hej"],
  "Portuguese (Brazil)": ["Olá", "Como vai?", "Bom dia", "Oi", "Tudo bem?"],
  "Portuguese (Portugal)": ["Olá", "Como vai?", "Bom dia", "Boas", "Tudo bem?"],
  "Russian": ["Привет", "Как дела?", "Доброе утро", "Здравствуйте", "Добрый день"],
  "Spanish (Spain)": ["Hola", "¿Cómo estás?", "¿Qué tal?", "Buenos días", "¿Cómo va?"],
  "Spanish (Mexico)": ["Hola", "¿Cómo estás?", "¿Qué tal?", "Buenos días", "¿Qué onda?"],
  "Swedish": ["Hej", "Hur mår du?", "God dag", "Hej, där", "God morgon"],
  "Tamil": ["வணக்கம்", "எப்படி இருக்கிறீர்கள்?", "நன்றி", "காலை வணக்கம்", "ஹலோ"],
  "Turkish": ["Merhaba", "Nasıl gidiyor?", "Günaydın", "Selam", "İyi günler"],
  "Vietnamese": ["Xin chào", "Bạn thế nào?", "Chào buổi sáng", "Chào buổi tối", "Chào bạn"],
};
