const nativeLanguageCodes = {
  "Arabic": "ar-XA",
  "Azerbaijani": "az-AZ",
  "Bengali": "bn-IN",
  "Danish": "da-DK",
  "English (US)": "en-US",
  "English (UK)": "en-GB",
  "English (Australia)": "en-AU",
  "Filipino": "fil-PH",
  "French (Canada)": "fr-CA",
  "French (France)": "fr-FR",
  "Gujarati": "gu-IN",
  "Hindi": "hi-IN",
  "German": "de-DE",
  "Indonesian": "id-ID",
  "Italian": "it-IT",
  "Japanese": "ja-JP",
  "Korean": "ko-KR",
  "Malay": "ms-MY",
  "Malayalam": "ml-IN",
  "Mandarin Chinese": "cmn-TW",
  "Norwegian": "nb-NO",
  "Polish": "pl-PL",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  "Russian": "ru-RU",
  "Spanish (Spain)": "es-ES",
  "Spanish (Mexico)": "es-US",
  "Swedish": "sv-SE",
  "Tamil": "ta-IN",
  "Turkish": "tr-TR",
  "Vietnamese": "vi-VN",
};
